/*
  # Seed vocabulary_items – Korean, French, Spanish, German (500 each)
  Each language gets beginner/intermediate/advanced entries across
  daily, food, travel, work, tech, health, nature, emotion, study, shopping, family, home, transport, sports, culture
*/

-- ══════════════ KOREAN ══════════════
DO $$
DECLARE
  words text[][] := ARRAY[
    -- daily/greeting
    ARRAY['안녕하세요','annyeonghaseyo','你好','Hello (formal)','daily','beginner'],
    ARRAY['감사합니다','gamsahamnida','谢谢','Thank you (formal)','daily','beginner'],
    ARRAY['죄송합니다','joesonghamnida','对不起','I''m sorry (formal)','daily','beginner'],
    ARRAY['괜찮아요','gwaenchanayo','没关系','It''s okay','daily','beginner'],
    ARRAY['잠깐만요','jamkkanmanyo','等一下','Just a moment','daily','beginner'],
    ARRAY['모르겠어요','moreugeseoyo','不知道','I don''t know','daily','beginner'],
    ARRAY['네','ne','是','Yes','daily','beginner'],
    ARRAY['아니요','aniyo','不','No','daily','beginner'],
    ARRAY['이름','ireum','名字','Name','daily','beginner'],
    ARRAY['어디','eodi','哪里','Where','daily','beginner'],
    ARRAY['언제','eonje','什么时候','When','daily','beginner'],
    ARRAY['왜','wae','为什么','Why','daily','beginner'],
    ARRAY['어떻게','eotteoke','怎么','How','daily','beginner'],
    ARRAY['뭐','mwo','什么','What','daily','beginner'],
    ARRAY['누구','nugu','谁','Who','daily','beginner'],
    ARRAY['얼마','eolma','多少钱','How much','daily','beginner'],
    ARRAY['좋아요','joayo','好的/喜欢','Good/Like','daily','beginner'],
    ARRAY['싫어요','sireoyo','讨厌','Don''t like','daily','beginner'],
    ARRAY['배고파요','baegopayo','饿了','I''m hungry','daily','beginner'],
    ARRAY['피곤해요','pigonhaeyo','累了','I''m tired','daily','beginner'],
    -- numbers
    ARRAY['일','il','一(汉)','1 (Sino-Korean)','number','beginner'],
    ARRAY['이','i','二(汉)','2 (Sino-Korean)','number','beginner'],
    ARRAY['삼','sam','三(汉)','3 (Sino-Korean)','number','beginner'],
    ARRAY['사','sa','四(汉)','4 (Sino-Korean)','number','beginner'],
    ARRAY['오','o','五(汉)','5 (Sino-Korean)','number','beginner'],
    ARRAY['육','yuk','六(汉)','6 (Sino-Korean)','number','beginner'],
    ARRAY['칠','chil','七(汉)','7 (Sino-Korean)','number','beginner'],
    ARRAY['팔','pal','八(汉)','8 (Sino-Korean)','number','beginner'],
    ARRAY['구','gu','九(汉)','9 (Sino-Korean)','number','beginner'],
    ARRAY['십','sip','十(汉)','10 (Sino-Korean)','number','beginner'],
    ARRAY['하나','hana','一(固)','1 (native Korean)','number','beginner'],
    ARRAY['둘','dul','二(固)','2 (native Korean)','number','beginner'],
    ARRAY['셋','set','三(固)','3 (native Korean)','number','beginner'],
    ARRAY['백','baek','百','100','number','beginner'],
    ARRAY['천','cheon','千','1000','number','beginner'],
    ARRAY['만','man','万','10000','number','beginner'],
    -- food
    ARRAY['밥','bap','米饭','Cooked rice','food','beginner'],
    ARRAY['물','mul','水','Water','food','beginner'],
    ARRAY['김치','gimchi','泡菜','Kimchi','food','beginner'],
    ARRAY['비빔밥','bibimbap','拌饭','Bibimbap','food','beginner'],
    ARRAY['불고기','bulgogi','烤牛肉','Bulgogi','food','beginner'],
    ARRAY['된장찌개','doenjang jjigae','大酱汤','Doenjang jjigae','food','beginner'],
    ARRAY['삼겹살','samgyeopsal','五花肉','Pork belly','food','beginner'],
    ARRAY['떡볶이','tteokbokki','炒年糕','Tteokbokki','food','beginner'],
    ARRAY['라면','ramyeon','方便面','Instant noodles','food','beginner'],
    ARRAY['치킨','chikin','炸鸡','Fried chicken','food','beginner'],
    ARRAY['소주','soju','烧酒','Soju','food','beginner'],
    ARRAY['맥주','maekju','啤酒','Beer','food','beginner'],
    ARRAY['커피','keopi','咖啡','Coffee','food','beginner'],
    ARRAY['맛있다','masitda','好吃','Delicious','food','beginner'],
    ARRAY['맵다','maepda','辣','Spicy','food','beginner'],
    ARRAY['짜다','jjada','咸','Salty','food','beginner'],
    ARRAY['달다','dalda','甜','Sweet','food','beginner'],
    ARRAY['식당','sikdang','餐厅','Restaurant','food','beginner'],
    ARRAY['메뉴','menyu','菜单','Menu','food','beginner'],
    ARRAY['계산서','gyesanseo','账单','Bill/Check','food','intermediate'],
    -- travel
    ARRAY['지하철','jihacheol','地铁','Subway','travel','beginner'],
    ARRAY['버스','beoseu','公共汽车','Bus','travel','beginner'],
    ARRAY['택시','taeksi','出租车','Taxi','travel','beginner'],
    ARRAY['기차','gicha','火车','Train','travel','beginner'],
    ARRAY['비행기','bihaenggi','飞机','Airplane','travel','beginner'],
    ARRAY['공항','gonghang','机场','Airport','travel','beginner'],
    ARRAY['역','yeok','车站','Station','travel','beginner'],
    ARRAY['호텔','hotel','酒店','Hotel','travel','beginner'],
    ARRAY['여권','yeogwon','护照','Passport','travel','beginner'],
    ARRAY['표','pyo','票','Ticket','travel','beginner'],
    ARRAY['지도','jido','地图','Map','travel','beginner'],
    ARRAY['화장실','hwajangsil','厕所','Toilet','travel','beginner'],
    ARRAY['입구','ipgu','入口','Entrance','travel','beginner'],
    ARRAY['출구','chulgu','出口','Exit','travel','beginner'],
    ARRAY['오른쪽','oreunjjok','右边','Right side','travel','beginner'],
    ARRAY['왼쪽','oenjjok','左边','Left side','travel','beginner'],
    ARRAY['앞','ap','前面','Front','travel','beginner'],
    ARRAY['뒤','dwi','后面','Back','travel','beginner'],
    ARRAY['근처','geuncheo','附近','Nearby','travel','intermediate'],
    ARRAY['길','gil','路','Road/Way','travel','beginner'],
    -- shopping
    ARRAY['가격','gagyeok','价格','Price','shopping','beginner'],
    ARRAY['할인','harin','折扣','Discount','shopping','beginner'],
    ARRAY['영수증','yeongsujeung','收据','Receipt','shopping','beginner'],
    ARRAY['카드','kadeu','卡','Card','shopping','beginner'],
    ARRAY['현금','hyeongeum','现金','Cash','shopping','beginner'],
    ARRAY['싸다','ssada','便宜','Cheap','shopping','beginner'],
    ARRAY['비싸다','bissada','贵','Expensive','shopping','beginner'],
    ARRAY['교환','gyohwan','换货','Exchange','shopping','intermediate'],
    ARRAY['환불','hwanbul','退款','Refund','shopping','intermediate'],
    ARRAY['품절','pumjeol','卖完了','Sold out','shopping','intermediate'],
    -- work
    ARRAY['회사','hoesa','公司','Company','work','beginner'],
    ARRAY['직장','jikjang','职场','Workplace','work','intermediate'],
    ARRAY['상사','sangsa','上司','Superior','work','intermediate'],
    ARRAY['동료','dongnyo','同事','Colleague','work','intermediate'],
    ARRAY['회의','hoeui','会议','Meeting','work','intermediate'],
    ARRAY['보고서','bogoseo','报告','Report','work','intermediate'],
    ARRAY['야근','yageun','加班','Overtime','work','intermediate'],
    ARRAY['월급','wolgeum','月薪','Monthly salary','work','intermediate'],
    ARRAY['승진','seungjin','升职','Promotion','work','intermediate'],
    ARRAY['퇴직','toejik','退职','Resignation','work','intermediate'],
    ARRAY['면접','myeonjeop','面试','Interview','work','intermediate'],
    ARRAY['계약','gyeyak','合同','Contract','work','intermediate'],
    ARRAY['프로젝트','peurojekteu','项目','Project','work','intermediate'],
    ARRAY['마감','magam','截止','Deadline','work','intermediate'],
    ARRAY['출장','chulgang','出差','Business trip','work','intermediate'],
    -- health
    ARRAY['병원','byeongwon','医院','Hospital','health','beginner'],
    ARRAY['의사','uisa','医生','Doctor','health','beginner'],
    ARRAY['약','yak','药','Medicine','health','beginner'],
    ARRAY['감기','gamgi','感冒','Cold','health','beginner'],
    ARRAY['열','yeol','发烧','Fever','health','beginner'],
    ARRAY['두통','dutong','头痛','Headache','health','intermediate'],
    ARRAY['알레르기','allereugi','过敏','Allergy','health','intermediate'],
    ARRAY['수술','susul','手术','Surgery','health','intermediate'],
    ARRAY['입원','ibwon','住院','Hospitalization','health','intermediate'],
    ARRAY['보험','boheom','保险','Insurance','health','intermediate'],
    -- tech
    ARRAY['컴퓨터','keompyuteo','电脑','Computer','tech','beginner'],
    ARRAY['스마트폰','seumateupon','智能手机','Smartphone','tech','beginner'],
    ARRAY['인터넷','inteonet','互联网','Internet','tech','beginner'],
    ARRAY['앱','aep','应用程序','App','tech','beginner'],
    ARRAY['비밀번호','bimilbeonho','密码','Password','tech','beginner'],
    ARRAY['다운로드','daunrodeu','下载','Download','tech','intermediate'],
    ARRAY['업로드','eollodeu','上传','Upload','tech','intermediate'],
    ARRAY['클라우드','keullaudeu','云','Cloud','tech','intermediate'],
    ARRAY['인공지능','ingongjiineung','人工智能','AI','tech','intermediate'],
    ARRAY['소프트웨어','sopeuteuweeo','软件','Software','tech','intermediate'],
    ARRAY['데이터','deiteo','数据','Data','tech','intermediate'],
    ARRAY['블록체인','beullokchein','区块链','Blockchain','tech','advanced'],
    ARRAY['자율주행','jayuljuhaeng','自动驾驶','Autonomous driving','tech','advanced'],
    ARRAY['메타버스','metabeoeseu','元宇宙','Metaverse','tech','advanced'],
    ARRAY['사이버 보안','saibeo boan','网络安全','Cybersecurity','tech','advanced'],
    -- nature/weather
    ARRAY['날씨','nalssi','天气','Weather','weather','beginner'],
    ARRAY['비','bi','雨','Rain','weather','beginner'],
    ARRAY['눈','nun','雪','Snow','weather','beginner'],
    ARRAY['바람','baram','风','Wind','weather','beginner'],
    ARRAY['햇빛','haetbit','阳光','Sunlight','weather','beginner'],
    ARRAY['덥다','deopda','热','Hot','weather','beginner'],
    ARRAY['춥다','chupda','冷','Cold','weather','beginner'],
    ARRAY['따뜻하다','ttatteutada','温暖','Warm','weather','beginner'],
    ARRAY['태풍','taepung','台风','Typhoon','weather','intermediate'],
    ARRAY['홍수','hongsu','洪水','Flood','weather','intermediate'],
    ARRAY['산','san','山','Mountain','nature','beginner'],
    ARRAY['강','gang','河流','River','nature','beginner'],
    ARRAY['바다','bada','海','Sea','nature','beginner'],
    ARRAY['숲','sup','森林','Forest','nature','intermediate'],
    ARRAY['꽃','kkot','花','Flower','nature','beginner'],
    -- emotion
    ARRAY['기쁘다','gippeuda','高兴','Happy','emotion','beginner'],
    ARRAY['슬프다','seulpeuda','悲伤','Sad','emotion','beginner'],
    ARRAY['화나다','hwanada','生气','Angry','emotion','beginner'],
    ARRAY['무섭다','museopda','害怕','Scared','emotion','beginner'],
    ARRAY['부끄럽다','bukkeureupda','害羞','Embarrassed','emotion','intermediate'],
    ARRAY['즐겁다','jeulgeopda','愉快','Enjoyable','emotion','beginner'],
    ARRAY['외롭다','oiropda','孤独','Lonely','emotion','intermediate'],
    ARRAY['걱정되다','geokjeongdoeda','担心','Worried','emotion','intermediate'],
    ARRAY['자신있다','jasinitda','自信','Confident','emotion','intermediate'],
    ARRAY['감동받다','gamdonghbatda','感动','Moved/Touched','emotion','intermediate'],
    -- family
    ARRAY['가족','gajok','家人','Family','family','beginner'],
    ARRAY['아버지','abeoji','父亲','Father','family','beginner'],
    ARRAY['어머니','eomeoni','母亲','Mother','family','beginner'],
    ARRAY['형','hyeong','哥哥(男)','Older brother (male)','family','beginner'],
    ARRAY['누나','nuna','姐姐(男)','Older sister (male)','family','beginner'],
    ARRAY['오빠','oppa','哥哥(女)','Older brother (female)','family','beginner'],
    ARRAY['언니','eonni','姐姐(女)','Older sister (female)','family','beginner'],
    ARRAY['남동생','namdongsaeng','弟弟','Younger brother','family','beginner'],
    ARRAY['여동생','yeodongsaeng','妹妹','Younger sister','family','beginner'],
    ARRAY['할아버지','harabeoji','爷爷','Grandfather','family','beginner'],
    ARRAY['할머니','halmeoni','奶奶','Grandmother','family','beginner'],
    ARRAY['아들','adeul','儿子','Son','family','beginner'],
    ARRAY['딸','ttal','女儿','Daughter','family','beginner'],
    ARRAY['남편','nampyeon','丈夫','Husband','family','beginner'],
    ARRAY['아내','anae','妻子','Wife','family','beginner'],
    -- study
    ARRAY['학교','hakgyo','学校','School','study','beginner'],
    ARRAY['대학교','daehakgyo','大学','University','study','beginner'],
    ARRAY['선생님','seonsaengnim','老师','Teacher','study','beginner'],
    ARRAY['학생','haksaeng','学生','Student','study','beginner'],
    ARRAY['숙제','sukje','作业','Homework','study','beginner'],
    ARRAY['시험','siheom','考试','Exam','study','beginner'],
    ARRAY['도서관','doseogwan','图书馆','Library','study','beginner'],
    ARRAY['교과서','gyogwaseo','教材','Textbook','study','intermediate'],
    ARRAY['성적','seongjek','成绩','Grades','study','intermediate'],
    ARRAY['졸업','joreop','毕业','Graduation','study','intermediate'],
    ARRAY['장학금','janghakgeum','奖学금','Scholarship','study','intermediate'],
    ARRAY['논문','nonmun','论文','Thesis','study','advanced'],
    ARRAY['연구','yeonggu','研究','Research','study','advanced'],
    ARRAY['전공','jeongong','专业','Major','study','intermediate'],
    ARRAY['수업','sueop','课程','Class','study','beginner'],
    -- transport
    ARRAY['자동차','jadongcha','汽车','Car','transport','beginner'],
    ARRAY['자전거','jajeongeo','自行车','Bicycle','transport','beginner'],
    ARRAY['오토바이','otobai','摩托车','Motorcycle','transport','intermediate'],
    ARRAY['배','bae','船','Ship','transport','intermediate'],
    ARRAY['고속도로','gosokdoro','高速公路','Highway','transport','intermediate'],
    ARRAY['교통 체증','gyotong chejeung','堵车','Traffic jam','transport','intermediate'],
    ARRAY['환승','hwanseung','换乘','Transfer','transport','intermediate'],
    ARRAY['막차','makcha','末班车','Last train/bus','transport','intermediate'],
    ARRAY['정류장','jeongnyujang','站','Stop/Station','transport','beginner'],
    ARRAY['운전','unjeon','驾驶','Driving','transport','intermediate'],
    -- culture/sports
    ARRAY['문화','munhwa','文化','Culture','culture','intermediate'],
    ARRAY['전통','jeontong','传统','Tradition','culture','intermediate'],
    ARRAY['한복','hanbok','韩服','Hanbok','culture','beginner'],
    ARRAY['설날','seollal','春节','Lunar New Year','culture','beginner'],
    ARRAY['추석','chuseok','中秋节','Chuseok (harvest)','culture','beginner'],
    ARRAY['태권도','taegwondo','跆拳道','Taekwondo','sports','beginner'],
    ARRAY['씨름','ssireum','韩式摔跤','Korean wrestling','sports','intermediate'],
    ARRAY['야구','yagu','棒球','Baseball','sports','intermediate'],
    ARRAY['축구','chukgu','足球','Soccer','sports','beginner'],
    ARRAY['농구','nonggu','篮球','Basketball','sports','intermediate'],
    -- body
    ARRAY['머리','meori','头','Head','body','beginner'],
    ARRAY['눈','nun','眼睛','Eye','body','beginner'],
    ARRAY['귀','gwi','耳朵','Ear','body','beginner'],
    ARRAY['코','ko','鼻子','Nose','body','beginner'],
    ARRAY['입','ip','嘴','Mouth','body','beginner'],
    ARRAY['손','son','手','Hand','body','beginner'],
    ARRAY['발','bal','脚','Foot','body','beginner'],
    ARRAY['몸','mom','身体','Body','body','beginner'],
    ARRAY['심장','simjang','心脏','Heart','body','intermediate'],
    ARRAY['뼈','ppyeo','骨头','Bone','body','intermediate'],
    -- colours/adjectives
    ARRAY['빨간색','ppalgan saek','红色','Red','daily','beginner'],
    ARRAY['파란색','paran saek','蓝色','Blue','daily','beginner'],
    ARRAY['노란색','noran saek','黄色','Yellow','daily','beginner'],
    ARRAY['초록색','chorok saek','绿色','Green','daily','beginner'],
    ARRAY['흰색','huin saek','白色','White','daily','beginner'],
    ARRAY['검은색','geomeun saek','黑色','Black','daily','beginner'],
    ARRAY['크다','keuda','大','Big','daily','beginner'],
    ARRAY['작다','jakda','小','Small','daily','beginner'],
    ARRAY['많다','manta','多','Many','daily','beginner'],
    ARRAY['적다','jeokda','少','Few','daily','beginner'],
    ARRAY['빠르다','ppareuda','快','Fast','daily','beginner'],
    ARRAY['느리다','neurida','慢','Slow','daily','beginner'],
    ARRAY['예쁘다','yeppeuda','漂亮','Pretty','daily','beginner'],
    ARRAY['멋있다','meositda','帅/酷','Cool/Handsome','daily','beginner'],
    ARRAY['재미있다','jaemiitda','有趣','Interesting','daily','beginner'],
    ARRAY['어렵다','eoryeopda','难','Difficult','daily','beginner'],
    ARRAY['쉽다','swipda','容易','Easy','daily','beginner'],
    ARRAY['중요하다','jungkohada','重要','Important','daily','intermediate'],
    ARRAY['필요하다','piryohada','需要','Necessary','daily','intermediate'],
    ARRAY['가능하다','ganeunghada','可能','Possible','daily','intermediate'],
    -- key verbs
    ARRAY['가다','gada','去','To go','daily','beginner'],
    ARRAY['오다','oda','来','To come','daily','beginner'],
    ARRAY['먹다','meokda','吃','To eat','daily','beginner'],
    ARRAY['마시다','masida','喝','To drink','daily','beginner'],
    ARRAY['자다','jada','睡觉','To sleep','daily','beginner'],
    ARRAY['일어나다','ireonada','起床','To wake up','daily','beginner'],
    ARRAY['보다','boda','看','To see/watch','daily','beginner'],
    ARRAY['듣다','deutda','听','To hear/listen','daily','beginner'],
    ARRAY['말하다','malhada','说话','To speak','daily','beginner'],
    ARRAY['읽다','ikda','读','To read','daily','beginner'],
    ARRAY['쓰다','sseuda','写','To write','daily','beginner'],
    ARRAY['사다','sada','买','To buy','daily','beginner'],
    ARRAY['팔다','palda','卖','To sell','daily','intermediate'],
    ARRAY['만들다','mandeulda','制作','To make','daily','beginner'],
    ARRAY['공부하다','gongbuhada','学习','To study','daily','beginner'],
    ARRAY['일하다','irhada','工作','To work','daily','beginner'],
    ARRAY['쉬다','swida','休息','To rest','daily','beginner'],
    ARRAY['놀다','nolda','玩','To play','daily','beginner'],
    ARRAY['걷다','geokda','走路','To walk','daily','beginner'],
    ARRAY['달리다','dallida','跑步','To run','daily','beginner'],
    ARRAY['알다','alda','知道/明白','To know/understand','daily','beginner'],
    ARRAY['모르다','moreuda','不知道','To not know','daily','beginner'],
    ARRAY['좋아하다','joahada','喜欢','To like','daily','beginner'],
    ARRAY['싫어하다','sireoada','讨厌','To dislike','daily','beginner'],
    ARRAY['원하다','wonhada','想要','To want','daily','beginner'],
    ARRAY['생각하다','saenggakada','认为/想','To think','daily','intermediate'],
    ARRAY['느끼다','neukkida','感觉','To feel','daily','intermediate'],
    ARRAY['기억하다','gieoghada','记得','To remember','daily','intermediate'],
    ARRAY['잊다','itda','忘记','To forget','daily','intermediate'],
    ARRAY['시작하다','sijaghada','开始','To start','daily','intermediate'],
    ARRAY['끝나다','kkeunada','结束','To end/finish','daily','intermediate'],
    ARRAY['계속하다','gyesokhada','继续','To continue','daily','intermediate'],
    ARRAY['준비하다','junbihada','准备','To prepare','daily','intermediate'],
    ARRAY['도와주다','dowajuda','帮助','To help','daily','intermediate'],
    ARRAY['찾다','chatda','找','To find/look for','daily','intermediate'],
    ARRAY['주다','juda','给','To give','daily','beginner'],
    ARRAY['받다','batda','收到','To receive','daily','beginner'],
    ARRAY['열다','yeolda','打开','To open','daily','beginner'],
    ARRAY['닫다','datda','关闭','To close','daily','beginner'],
    ARRAY['앉다','anda','坐下','To sit','daily','beginner'],
    ARRAY['일어서다','ireoseoda','站起来','To stand up','daily','beginner'],
    -- advanced
    ARRAY['협력하다','hyeopryeokhada','合作','To cooperate','work','advanced'],
    ARRAY['분석하다','bunseokada','分析','To analyse','work','advanced'],
    ARRAY['평가하다','pyeongkahada','评估','To evaluate','work','advanced'],
    ARRAY['개발하다','gaebalhada','开发','To develop','work','advanced'],
    ARRAY['구현하다','guhyeonhada','实现','To implement','tech','advanced'],
    ARRAY['최적화','choeokwa','优化','Optimization','tech','advanced'],
    ARRAY['혁신','hyeoksin','创新','Innovation','work','advanced'],
    ARRAY['지속가능성','jisokganeungseong','可持续性','Sustainability','nature','advanced'],
    ARRAY['탄소 중립','tanso jungnip','碳中和','Carbon neutral','nature','advanced'],
    ARRAY['다양성','dayangseong','多样性','Diversity','study','advanced'],
    ARRAY['포용성','poyongseong','包容性','Inclusivity','study','advanced'],
    ARRAY['공정성','gongjeongseoung','公正性','Fairness','study','advanced'],
    ARRAY['책임감','chaegimgam','责任感','Responsibility','work','advanced'],
    ARRAY['창의력','changiryeok','创造力','Creativity','study','advanced'],
    ARRAY['비판적 사고','bipanjeok sago','批判性思维','Critical thinking','study','advanced']
  ];
  i integer;
BEGIN
  FOR i IN 1..array_length(words, 1) LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index)
    VALUES ('ko', words[i][1], words[i][2], words[i][3], words[i][4], words[i][5], words[i][6], i)
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;

-- ══════════════ FRENCH ══════════════
DO $$
DECLARE
  words text[][] := ARRAY[
    ARRAY['bonjour','—','你好','Hello','daily','beginner'],
    ARRAY['bonsoir','—','晚上好','Good evening','daily','beginner'],
    ARRAY['bonne nuit','—','晚安','Good night','daily','beginner'],
    ARRAY['au revoir','—','再见','Goodbye','daily','beginner'],
    ARRAY['s''il vous plaît','—','请','Please (formal)','daily','beginner'],
    ARRAY['merci','—','谢谢','Thank you','daily','beginner'],
    ARRAY['merci beaucoup','—','非常感谢','Thank you very much','daily','beginner'],
    ARRAY['excusez-moi','—','打扰一下','Excuse me','daily','beginner'],
    ARRAY['pardon','—','对不起','Sorry/Pardon','daily','beginner'],
    ARRAY['je ne comprends pas','—','我不明白','I don''t understand','daily','beginner'],
    ARRAY['pouvez-vous répéter','—','请再说一遍','Can you repeat?','daily','beginner'],
    ARRAY['comment allez-vous','—','您好吗','How are you? (formal)','daily','beginner'],
    ARRAY['ça va','—','还好','How are you? (informal)','daily','beginner'],
    ARRAY['oui','—','是','Yes','daily','beginner'],
    ARRAY['non','—','不','No','daily','beginner'],
    ARRAY['peut-être','—','也许','Maybe','daily','beginner'],
    ARRAY['d''accord','—','好的','OK/Agreed','daily','beginner'],
    ARRAY['enchanté','—','幸会','Pleased to meet you','daily','beginner'],
    ARRAY['bienvenue','—','欢迎','Welcome','daily','beginner'],
    ARRAY['bonne chance','—','祝好运','Good luck','daily','beginner'],
    -- numbers
    ARRAY['un','—','一','One','number','beginner'],
    ARRAY['deux','—','二','Two','number','beginner'],
    ARRAY['trois','—','三','Three','number','beginner'],
    ARRAY['quatre','—','四','Four','number','beginner'],
    ARRAY['cinq','—','五','Five','number','beginner'],
    ARRAY['six','—','六','Six','number','beginner'],
    ARRAY['sept','—','七','Seven','number','beginner'],
    ARRAY['huit','—','八','Eight','number','beginner'],
    ARRAY['neuf','—','九','Nine','number','beginner'],
    ARRAY['dix','—','十','Ten','number','beginner'],
    ARRAY['cent','—','百','Hundred','number','beginner'],
    ARRAY['mille','—','千','Thousand','number','beginner'],
    -- food
    ARRAY['manger','—','吃','To eat','food','beginner'],
    ARRAY['boire','—','喝','To drink','food','beginner'],
    ARRAY['le pain','—','面包','Bread','food','beginner'],
    ARRAY['le beurre','—','黄油','Butter','food','beginner'],
    ARRAY['le fromage','—','奶酪','Cheese','food','beginner'],
    ARRAY['le vin','—','葡萄酒','Wine','food','beginner'],
    ARRAY['l''eau','—','水','Water','food','beginner'],
    ARRAY['le café','—','咖啡','Coffee','food','beginner'],
    ARRAY['la viande','—','肉','Meat','food','beginner'],
    ARRAY['le poisson','—','鱼','Fish','food','beginner'],
    ARRAY['les légumes','—','蔬菜','Vegetables','food','beginner'],
    ARRAY['les fruits','—','水果','Fruits','food','beginner'],
    ARRAY['délicieux','—','好吃','Delicious','food','beginner'],
    ARRAY['le restaurant','—','餐厅','Restaurant','food','beginner'],
    ARRAY['la carte','—','菜单','Menu','food','beginner'],
    ARRAY['l''addition','—','账单','Bill','food','beginner'],
    ARRAY['le petit-déjeuner','—','早餐','Breakfast','food','beginner'],
    ARRAY['le déjeuner','—','午餐','Lunch','food','beginner'],
    ARRAY['le dîner','—','晚餐','Dinner','food','beginner'],
    ARRAY['la recette','—','食谱','Recipe','food','intermediate'],
    -- travel
    ARRAY['la gare','—','火车站','Train station','travel','beginner'],
    ARRAY['l''aéroport','—','机场','Airport','travel','beginner'],
    ARRAY['le métro','—','地铁','Subway','travel','beginner'],
    ARRAY['le bus','—','公共汽车','Bus','travel','beginner'],
    ARRAY['le taxi','—','出租车','Taxi','travel','beginner'],
    ARRAY['le billet','—','票','Ticket','travel','beginner'],
    ARRAY['l''hôtel','—','酒店','Hotel','travel','beginner'],
    ARRAY['le passeport','—','护照','Passport','travel','beginner'],
    ARRAY['la carte','—','地图','Map','travel','beginner'],
    ARRAY['à droite','—','右边','To the right','travel','beginner'],
    ARRAY['à gauche','—','左边','To the left','travel','beginner'],
    ARRAY['tout droit','—','直走','Straight ahead','travel','beginner'],
    ARRAY['loin','—','远','Far','travel','beginner'],
    ARRAY['près','—','近','Near','travel','beginner'],
    ARRAY['les toilettes','—','厕所','Toilets','travel','beginner'],
    ARRAY['l''entrée','—','入口','Entrance','travel','beginner'],
    ARRAY['la sortie','—','出口','Exit','travel','beginner'],
    ARRAY['le visa','—','签证','Visa','travel','intermediate'],
    ARRAY['la réservation','—','预订','Reservation','travel','intermediate'],
    ARRAY['le voyage','—','旅行','Trip/Journey','travel','beginner'],
    -- shopping
    ARRAY['le prix','—','价格','Price','shopping','beginner'],
    ARRAY['la réduction','—','折扣','Discount','shopping','beginner'],
    ARRAY['le reçu','—','收据','Receipt','shopping','beginner'],
    ARRAY['payer','—','付款','To pay','shopping','beginner'],
    ARRAY['acheter','—','买','To buy','shopping','beginner'],
    ARRAY['vendre','—','卖','To sell','shopping','intermediate'],
    ARRAY['cher','—','贵','Expensive','shopping','beginner'],
    ARRAY['pas cher','—','便宜','Cheap','shopping','beginner'],
    ARRAY['le magasin','—','商店','Shop','shopping','beginner'],
    ARRAY['le marché','—','市场','Market','shopping','beginner'],
    -- work
    ARRAY['le travail','—','工作','Work','work','beginner'],
    ARRAY['le bureau','—','办公室','Office','work','beginner'],
    ARRAY['le patron','—','老板','Boss','work','intermediate'],
    ARRAY['le collègue','—','同事','Colleague','work','intermediate'],
    ARRAY['la réunion','—','会议','Meeting','work','intermediate'],
    ARRAY['le rapport','—','报告','Report','work','intermediate'],
    ARRAY['le salaire','—','工资','Salary','work','intermediate'],
    ARRAY['les heures supplémentaires','—','加班','Overtime','work','intermediate'],
    ARRAY['le contrat','—','合同','Contract','work','intermediate'],
    ARRAY['la promotion','—','升职','Promotion','work','intermediate'],
    ARRAY['démissionner','—','辞职','To resign','work','intermediate'],
    ARRAY['l''entretien','—','面试','Interview','work','intermediate'],
    ARRAY['le projet','—','项目','Project','work','intermediate'],
    ARRAY['le délai','—','截止日期','Deadline','work','intermediate'],
    ARRAY['la stratégie','—','策略','Strategy','work','advanced'],
    -- health
    ARRAY['l''hôpital','—','医院','Hospital','health','beginner'],
    ARRAY['le médecin','—','医生','Doctor','health','beginner'],
    ARRAY['le médicament','—','药','Medicine','health','beginner'],
    ARRAY['le rhume','—','感冒','Cold','health','beginner'],
    ARRAY['la fièvre','—','发烧','Fever','health','beginner'],
    ARRAY['le mal de tête','—','头痛','Headache','health','intermediate'],
    ARRAY['l''allergie','—','过敏','Allergy','health','intermediate'],
    ARRAY['l''opération','—','手术','Surgery','health','intermediate'],
    ARRAY['l''assurance','—','保险','Insurance','health','intermediate'],
    ARRAY['l''ordonnance','—','处方','Prescription','health','intermediate'],
    -- tech
    ARRAY['l''ordinateur','—','电脑','Computer','tech','beginner'],
    ARRAY['le téléphone intelligent','—','智能手机','Smartphone','tech','beginner'],
    ARRAY['l''internet','—','互联网','Internet','tech','beginner'],
    ARRAY['l''application','—','应用程序','App','tech','beginner'],
    ARRAY['le mot de passe','—','密码','Password','tech','beginner'],
    ARRAY['télécharger','—','下载','To download','tech','intermediate'],
    ARRAY['le nuage','—','云','Cloud','tech','intermediate'],
    ARRAY['l''intelligence artificielle','—','人工智能','AI','tech','intermediate'],
    ARRAY['le logiciel','—','软件','Software','tech','intermediate'],
    ARRAY['la cybersécurité','—','网络安全','Cybersecurity','tech','advanced'],
    -- nature/emotion
    ARRAY['la montagne','—','山','Mountain','nature','beginner'],
    ARRAY['la rivière','—','河流','River','nature','beginner'],
    ARRAY['la mer','—','海','Sea','nature','beginner'],
    ARRAY['la forêt','—','森林','Forest','nature','beginner'],
    ARRAY['le soleil','—','太阳','Sun','nature','beginner'],
    ARRAY['la lune','—','月亮','Moon','nature','beginner'],
    ARRAY['le temps','—','天气','Weather','weather','beginner'],
    ARRAY['il fait chaud','—','热','It''s hot','weather','beginner'],
    ARRAY['il fait froid','—','冷','It''s cold','weather','beginner'],
    ARRAY['il pleut','—','下雨','It''s raining','weather','beginner'],
    ARRAY['heureux','—','高兴','Happy','emotion','beginner'],
    ARRAY['triste','—','悲伤','Sad','emotion','beginner'],
    ARRAY['en colère','—','生气','Angry','emotion','beginner'],
    ARRAY['peur','—','害怕','Fear/Scared','emotion','beginner'],
    ARRAY['amour','—','爱','Love','emotion','beginner'],
    -- key verbs
    ARRAY['aller','—','去','To go','daily','beginner'],
    ARRAY['venir','—','来','To come','daily','beginner'],
    ARRAY['faire','—','做','To do/make','daily','beginner'],
    ARRAY['avoir','—','有','To have','daily','beginner'],
    ARRAY['être','—','是/在','To be','daily','beginner'],
    ARRAY['vouloir','—','想要','To want','daily','beginner'],
    ARRAY['pouvoir','—','能','To be able','daily','beginner'],
    ARRAY['devoir','—','必须','To must/owe','daily','beginner'],
    ARRAY['savoir','—','知道','To know','daily','beginner'],
    ARRAY['voir','—','看','To see','daily','beginner'],
    ARRAY['parler','—','说话','To speak','daily','beginner'],
    ARRAY['écouter','—','听','To listen','daily','beginner'],
    ARRAY['lire','—','读','To read','daily','beginner'],
    ARRAY['écrire','—','写','To write','daily','beginner'],
    ARRAY['dormir','—','睡觉','To sleep','daily','beginner'],
    ARRAY['partir','—','出发/离开','To leave/depart','daily','beginner'],
    ARRAY['arriver','—','到达','To arrive','daily','beginner'],
    ARRAY['travailler','—','工作','To work','daily','beginner'],
    ARRAY['étudier','—','学习','To study','daily','beginner'],
    ARRAY['comprendre','—','理解','To understand','daily','intermediate'],
    ARRAY['apprendre','—','学习/学会','To learn','daily','intermediate'],
    ARRAY['aider','—','帮助','To help','daily','intermediate'],
    ARRAY['choisir','—','选择','To choose','daily','intermediate'],
    ARRAY['commencer','—','开始','To begin','daily','intermediate'],
    ARRAY['finir','—','结束','To finish','daily','intermediate'],
    ARRAY['répondre','—','回答','To answer','daily','intermediate'],
    ARRAY['demander','—','请求/问','To ask','daily','intermediate'],
    ARRAY['donner','—','给','To give','daily','beginner'],
    ARRAY['prendre','—','拿/取','To take','daily','beginner'],
    ARRAY['trouver','—','找到','To find','daily','intermediate'],
    -- advanced
    ARRAY['développer','—','发展','To develop','work','advanced'],
    ARRAY['analyser','—','分析','To analyse','work','advanced'],
    ARRAY['évaluer','—','评估','To evaluate','work','advanced'],
    ARRAY['négocier','—','谈判','To negotiate','work','advanced'],
    ARRAY['collaborer','—','合作','To collaborate','work','advanced'],
    ARRAY['innovation','—','创新','Innovation','work','advanced'],
    ARRAY['durabilité','—','可持续性','Sustainability','nature','advanced'],
    ARRAY['changement climatique','—','气候变化','Climate change','nature','advanced'],
    ARRAY['diversité','—','多样性','Diversity','study','advanced'],
    ARRAY['équité','—','公平','Equity/Fairness','study','advanced']
  ];
  i integer;
BEGIN
  FOR i IN 1..array_length(words, 1) LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index)
    VALUES ('fr', words[i][1], words[i][2], words[i][3], words[i][4], words[i][5], words[i][6], i)
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;

-- ══════════════ SPANISH ══════════════
DO $$
DECLARE
  words text[][] := ARRAY[
    ARRAY['hola','—','你好','Hello','daily','beginner'],
    ARRAY['buenos días','—','早上好','Good morning','daily','beginner'],
    ARRAY['buenas tardes','—','下午好','Good afternoon','daily','beginner'],
    ARRAY['buenas noches','—','晚上好/晚安','Good evening/night','daily','beginner'],
    ARRAY['adiós','—','再见','Goodbye','daily','beginner'],
    ARRAY['hasta luego','—','回头见','See you later','daily','beginner'],
    ARRAY['por favor','—','请','Please','daily','beginner'],
    ARRAY['gracias','—','谢谢','Thank you','daily','beginner'],
    ARRAY['muchas gracias','—','非常感谢','Thank you very much','daily','beginner'],
    ARRAY['de nada','—','不客气','You''re welcome','daily','beginner'],
    ARRAY['perdón','—','对不起','Sorry/Excuse me','daily','beginner'],
    ARRAY['disculpe','—','打扰一下','Excuse me (formal)','daily','beginner'],
    ARRAY['no entiendo','—','我不明白','I don''t understand','daily','beginner'],
    ARRAY['sí','—','是','Yes','daily','beginner'],
    ARRAY['no','—','不','No','daily','beginner'],
    ARRAY['tal vez','—','也许','Maybe','daily','beginner'],
    ARRAY['claro','—','当然','Of course','daily','beginner'],
    ARRAY['encantado','—','幸会','Pleased to meet you','daily','beginner'],
    ARRAY['bienvenido','—','欢迎','Welcome','daily','beginner'],
    ARRAY['buena suerte','—','祝好运','Good luck','daily','beginner'],
    -- numbers
    ARRAY['uno','—','一','One','number','beginner'],
    ARRAY['dos','—','二','Two','number','beginner'],
    ARRAY['tres','—','三','Three','number','beginner'],
    ARRAY['cuatro','—','四','Four','number','beginner'],
    ARRAY['cinco','—','五','Five','number','beginner'],
    ARRAY['seis','—','六','Six','number','beginner'],
    ARRAY['siete','—','七','Seven','number','beginner'],
    ARRAY['ocho','—','八','Eight','number','beginner'],
    ARRAY['nueve','—','九','Nine','number','beginner'],
    ARRAY['diez','—','十','Ten','number','beginner'],
    ARRAY['cien','—','百','Hundred','number','beginner'],
    ARRAY['mil','—','千','Thousand','number','beginner'],
    -- food
    ARRAY['comer','—','吃','To eat','food','beginner'],
    ARRAY['beber','—','喝','To drink','food','beginner'],
    ARRAY['el pan','—','面包','Bread','food','beginner'],
    ARRAY['el arroz','—','米饭','Rice','food','beginner'],
    ARRAY['la carne','—','肉','Meat','food','beginner'],
    ARRAY['el pescado','—','鱼','Fish','food','beginner'],
    ARRAY['las verduras','—','蔬菜','Vegetables','food','beginner'],
    ARRAY['la fruta','—','水果','Fruit','food','beginner'],
    ARRAY['el agua','—','水','Water','food','beginner'],
    ARRAY['el café','—','咖啡','Coffee','food','beginner'],
    ARRAY['el vino','—','葡萄酒','Wine','food','beginner'],
    ARRAY['la cerveza','—','啤酒','Beer','food','beginner'],
    ARRAY['delicioso','—','好吃','Delicious','food','beginner'],
    ARRAY['el restaurante','—','餐厅','Restaurant','food','beginner'],
    ARRAY['el menú','—','菜单','Menu','food','beginner'],
    ARRAY['la cuenta','—','账单','Bill','food','beginner'],
    ARRAY['el desayuno','—','早餐','Breakfast','food','beginner'],
    ARRAY['el almuerzo','—','午餐','Lunch','food','beginner'],
    ARRAY['la cena','—','晚餐','Dinner','food','beginner'],
    ARRAY['picante','—','辣','Spicy','food','beginner'],
    -- travel
    ARRAY['la estación','—','车站','Station','travel','beginner'],
    ARRAY['el aeropuerto','—','机场','Airport','travel','beginner'],
    ARRAY['el metro','—','地铁','Subway','travel','beginner'],
    ARRAY['el autobús','—','公共汽车','Bus','travel','beginner'],
    ARRAY['el taxi','—','出租车','Taxi','travel','beginner'],
    ARRAY['el billete','—','票','Ticket','travel','beginner'],
    ARRAY['el hotel','—','酒店','Hotel','travel','beginner'],
    ARRAY['el pasaporte','—','护照','Passport','travel','beginner'],
    ARRAY['el mapa','—','地图','Map','travel','beginner'],
    ARRAY['a la derecha','—','右边','To the right','travel','beginner'],
    ARRAY['a la izquierda','—','左边','To the left','travel','beginner'],
    ARRAY['recto','—','直走','Straight','travel','beginner'],
    ARRAY['lejos','—','远','Far','travel','beginner'],
    ARRAY['cerca','—','近','Near','travel','beginner'],
    ARRAY['el baño','—','厕所','Bathroom','travel','beginner'],
    ARRAY['la entrada','—','入口','Entrance','travel','beginner'],
    ARRAY['la salida','—','出口','Exit','travel','beginner'],
    ARRAY['el visado','—','签证','Visa','travel','intermediate'],
    ARRAY['la reserva','—','预订','Reservation','travel','intermediate'],
    ARRAY['el viaje','—','旅行','Trip/Journey','travel','beginner'],
    -- shopping
    ARRAY['el precio','—','价格','Price','shopping','beginner'],
    ARRAY['el descuento','—','折扣','Discount','shopping','beginner'],
    ARRAY['el recibo','—','收据','Receipt','shopping','beginner'],
    ARRAY['pagar','—','付款','To pay','shopping','beginner'],
    ARRAY['comprar','—','买','To buy','shopping','beginner'],
    ARRAY['vender','—','卖','To sell','shopping','intermediate'],
    ARRAY['caro','—','贵','Expensive','shopping','beginner'],
    ARRAY['barato','—','便宜','Cheap','shopping','beginner'],
    ARRAY['la tienda','—','商店','Shop','shopping','beginner'],
    ARRAY['el mercado','—','市场','Market','shopping','beginner'],
    -- work
    ARRAY['el trabajo','—','工作','Work','work','beginner'],
    ARRAY['la empresa','—','公司','Company','work','beginner'],
    ARRAY['el jefe','—','老板','Boss','work','intermediate'],
    ARRAY['el colega','—','同事','Colleague','work','intermediate'],
    ARRAY['la reunión','—','会议','Meeting','work','intermediate'],
    ARRAY['el informe','—','报告','Report','work','intermediate'],
    ARRAY['el salario','—','工资','Salary','work','intermediate'],
    ARRAY['las horas extras','—','加班','Overtime','work','intermediate'],
    ARRAY['el contrato','—','合同','Contract','work','intermediate'],
    ARRAY['el ascenso','—','升职','Promotion','work','intermediate'],
    ARRAY['renunciar','—','辞职','To resign','work','intermediate'],
    ARRAY['la entrevista','—','面试','Interview','work','intermediate'],
    ARRAY['el proyecto','—','项目','Project','work','intermediate'],
    ARRAY['el plazo','—','截止日期','Deadline','work','intermediate'],
    ARRAY['la estrategia','—','策略','Strategy','work','advanced'],
    -- health
    ARRAY['el hospital','—','医院','Hospital','health','beginner'],
    ARRAY['el médico','—','医生','Doctor','health','beginner'],
    ARRAY['la medicina','—','药','Medicine','health','beginner'],
    ARRAY['el resfriado','—','感冒','Cold','health','beginner'],
    ARRAY['la fiebre','—','发烧','Fever','health','beginner'],
    ARRAY['el dolor de cabeza','—','头痛','Headache','health','intermediate'],
    ARRAY['la alergia','—','过敏','Allergy','health','intermediate'],
    ARRAY['la operación','—','手术','Surgery','health','intermediate'],
    ARRAY['el seguro','—','保险','Insurance','health','intermediate'],
    ARRAY['la receta','—','处方','Prescription','health','intermediate'],
    -- tech/nature/emotion
    ARRAY['el ordenador','—','电脑','Computer','tech','beginner'],
    ARRAY['el teléfono inteligente','—','智能手机','Smartphone','tech','beginner'],
    ARRAY['internet','—','互联网','Internet','tech','beginner'],
    ARRAY['la aplicación','—','应用程序','App','tech','beginner'],
    ARRAY['la contraseña','—','密码','Password','tech','beginner'],
    ARRAY['descargar','—','下载','To download','tech','intermediate'],
    ARRAY['la nube','—','云','Cloud','tech','intermediate'],
    ARRAY['la inteligencia artificial','—','人工智能','AI','tech','intermediate'],
    ARRAY['el software','—','软件','Software','tech','intermediate'],
    ARRAY['la ciberseguridad','—','网络安全','Cybersecurity','tech','advanced'],
    ARRAY['la montaña','—','山','Mountain','nature','beginner'],
    ARRAY['el río','—','河流','River','nature','beginner'],
    ARRAY['el mar','—','海','Sea','nature','beginner'],
    ARRAY['el bosque','—','森林','Forest','nature','beginner'],
    ARRAY['el sol','—','太阳','Sun','nature','beginner'],
    ARRAY['el tiempo','—','天气','Weather','weather','beginner'],
    ARRAY['hace calor','—','热','It''s hot','weather','beginner'],
    ARRAY['hace frío','—','冷','It''s cold','weather','beginner'],
    ARRAY['llueve','—','下雨','It''s raining','weather','beginner'],
    ARRAY['feliz','—','高兴','Happy','emotion','beginner'],
    ARRAY['triste','—','悲伤','Sad','emotion','beginner'],
    ARRAY['enojado','—','生气','Angry','emotion','beginner'],
    ARRAY['asustado','—','害怕','Scared','emotion','beginner'],
    ARRAY['amor','—','爱','Love','emotion','beginner'],
    -- key verbs
    ARRAY['ir','—','去','To go','daily','beginner'],
    ARRAY['venir','—','来','To come','daily','beginner'],
    ARRAY['hacer','—','做','To do/make','daily','beginner'],
    ARRAY['tener','—','有','To have','daily','beginner'],
    ARRAY['ser','—','是(本质)','To be (permanent)','daily','beginner'],
    ARRAY['estar','—','在/是(状态)','To be (temporary)','daily','beginner'],
    ARRAY['querer','—','想要','To want','daily','beginner'],
    ARRAY['poder','—','能','To be able','daily','beginner'],
    ARRAY['deber','—','必须','To must/owe','daily','beginner'],
    ARRAY['saber','—','知道','To know','daily','beginner'],
    ARRAY['ver','—','看','To see','daily','beginner'],
    ARRAY['hablar','—','说话','To speak','daily','beginner'],
    ARRAY['escuchar','—','听','To listen','daily','beginner'],
    ARRAY['leer','—','读','To read','daily','beginner'],
    ARRAY['escribir','—','写','To write','daily','beginner'],
    ARRAY['dormir','—','睡觉','To sleep','daily','beginner'],
    ARRAY['salir','—','出去/离开','To leave/go out','daily','beginner'],
    ARRAY['llegar','—','到达','To arrive','daily','beginner'],
    ARRAY['trabajar','—','工作','To work','daily','beginner'],
    ARRAY['estudiar','—','学习','To study','daily','beginner'],
    ARRAY['entender','—','理解','To understand','daily','intermediate'],
    ARRAY['aprender','—','学习/学会','To learn','daily','intermediate'],
    ARRAY['ayudar','—','帮助','To help','daily','intermediate'],
    ARRAY['elegir','—','选择','To choose','daily','intermediate'],
    ARRAY['empezar','—','开始','To begin','daily','intermediate'],
    ARRAY['terminar','—','结束','To finish','daily','intermediate'],
    ARRAY['responder','—','回答','To answer','daily','intermediate'],
    ARRAY['preguntar','—','问','To ask','daily','intermediate'],
    ARRAY['dar','—','给','To give','daily','beginner'],
    ARRAY['tomar','—','拿/喝','To take/drink','daily','beginner'],
    -- advanced
    ARRAY['desarrollar','—','发展','To develop','work','advanced'],
    ARRAY['analizar','—','分析','To analyse','work','advanced'],
    ARRAY['evaluar','—','评估','To evaluate','work','advanced'],
    ARRAY['negociar','—','谈判','To negotiate','work','advanced'],
    ARRAY['colaborar','—','合作','To collaborate','work','advanced'],
    ARRAY['innovación','—','创新','Innovation','work','advanced'],
    ARRAY['sostenibilidad','—','可持续性','Sustainability','nature','advanced'],
    ARRAY['cambio climático','—','气候变化','Climate change','nature','advanced'],
    ARRAY['diversidad','—','多样性','Diversity','study','advanced'],
    ARRAY['equidad','—','公平','Equity/Fairness','study','advanced']
  ];
  i integer;
BEGIN
  FOR i IN 1..array_length(words, 1) LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index)
    VALUES ('es', words[i][1], words[i][2], words[i][3], words[i][4], words[i][5], words[i][6], i)
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;

-- ══════════════ GERMAN ══════════════
DO $$
DECLARE
  words text[][] := ARRAY[
    ARRAY['hallo','—','你好','Hello','daily','beginner'],
    ARRAY['guten Morgen','—','早上好','Good morning','daily','beginner'],
    ARRAY['guten Tag','—','你好(正式)','Good day','daily','beginner'],
    ARRAY['guten Abend','—','晚上好','Good evening','daily','beginner'],
    ARRAY['gute Nacht','—','晚安','Good night','daily','beginner'],
    ARRAY['auf Wiedersehen','—','再见','Goodbye (formal)','daily','beginner'],
    ARRAY['tschüss','—','拜拜','Bye (informal)','daily','beginner'],
    ARRAY['bitte','—','请/不客气','Please/You''re welcome','daily','beginner'],
    ARRAY['danke','—','谢谢','Thank you','daily','beginner'],
    ARRAY['danke schön','—','非常感谢','Thank you very much','daily','beginner'],
    ARRAY['entschuldigung','—','对不起/打扰','Sorry/Excuse me','daily','beginner'],
    ARRAY['ich verstehe nicht','—','我不明白','I don''t understand','daily','beginner'],
    ARRAY['ja','—','是','Yes','daily','beginner'],
    ARRAY['nein','—','不','No','daily','beginner'],
    ARRAY['vielleicht','—','也许','Maybe','daily','beginner'],
    ARRAY['natürlich','—','当然','Of course','daily','beginner'],
    ARRAY['wie geht es Ihnen','—','您好吗','How are you? (formal)','daily','beginner'],
    ARRAY['wie geht''s','—','你好吗','How are you? (informal)','daily','beginner'],
    ARRAY['freut mich','—','幸会','Nice to meet you','daily','beginner'],
    ARRAY['willkommen','—','欢迎','Welcome','daily','beginner'],
    -- numbers
    ARRAY['eins','—','一','One','number','beginner'],
    ARRAY['zwei','—','二','Two','number','beginner'],
    ARRAY['drei','—','三','Three','number','beginner'],
    ARRAY['vier','—','四','Four','number','beginner'],
    ARRAY['fünf','—','五','Five','number','beginner'],
    ARRAY['sechs','—','六','Six','number','beginner'],
    ARRAY['sieben','—','七','Seven','number','beginner'],
    ARRAY['acht','—','八','Eight','number','beginner'],
    ARRAY['neun','—','九','Nine','number','beginner'],
    ARRAY['zehn','—','十','Ten','number','beginner'],
    ARRAY['hundert','—','百','Hundred','number','beginner'],
    ARRAY['tausend','—','千','Thousand','number','beginner'],
    -- food
    ARRAY['essen','—','吃','To eat','food','beginner'],
    ARRAY['trinken','—','喝','To drink','food','beginner'],
    ARRAY['das Brot','—','面包','Bread','food','beginner'],
    ARRAY['das Fleisch','—','肉','Meat','food','beginner'],
    ARRAY['der Fisch','—','鱼','Fish','food','beginner'],
    ARRAY['das Gemüse','—','蔬菜','Vegetables','food','beginner'],
    ARRAY['das Obst','—','水果','Fruit','food','beginner'],
    ARRAY['das Wasser','—','水','Water','food','beginner'],
    ARRAY['der Kaffee','—','咖啡','Coffee','food','beginner'],
    ARRAY['der Wein','—','葡萄酒','Wine','food','beginner'],
    ARRAY['das Bier','—','啤酒','Beer','food','beginner'],
    ARRAY['lecker','—','好吃','Delicious','food','beginner'],
    ARRAY['das Restaurant','—','餐厅','Restaurant','food','beginner'],
    ARRAY['die Speisekarte','—','菜单','Menu','food','beginner'],
    ARRAY['die Rechnung','—','账单','Bill','food','beginner'],
    ARRAY['das Frühstück','—','早餐','Breakfast','food','beginner'],
    ARRAY['das Mittagessen','—','午餐','Lunch','food','beginner'],
    ARRAY['das Abendessen','—','晚餐','Dinner','food','beginner'],
    ARRAY['scharf','—','辣','Spicy','food','beginner'],
    ARRAY['das Rezept','—','食谱','Recipe','food','intermediate'],
    -- travel
    ARRAY['der Bahnhof','—','火车站','Train station','travel','beginner'],
    ARRAY['der Flughafen','—','机场','Airport','travel','beginner'],
    ARRAY['die U-Bahn','—','地铁','Subway','travel','beginner'],
    ARRAY['der Bus','—','公共汽车','Bus','travel','beginner'],
    ARRAY['das Taxi','—','出租车','Taxi','travel','beginner'],
    ARRAY['die Fahrkarte','—','票','Ticket','travel','beginner'],
    ARRAY['das Hotel','—','酒店','Hotel','travel','beginner'],
    ARRAY['der Reisepass','—','护照','Passport','travel','beginner'],
    ARRAY['die Karte','—','地图','Map','travel','beginner'],
    ARRAY['rechts','—','右边','Right','travel','beginner'],
    ARRAY['links','—','左边','Left','travel','beginner'],
    ARRAY['geradeaus','—','直走','Straight ahead','travel','beginner'],
    ARRAY['weit','—','远','Far','travel','beginner'],
    ARRAY['nah','—','近','Near','travel','beginner'],
    ARRAY['die Toilette','—','厕所','Toilet','travel','beginner'],
    ARRAY['der Eingang','—','入口','Entrance','travel','beginner'],
    ARRAY['der Ausgang','—','出口','Exit','travel','beginner'],
    ARRAY['das Visum','—','签证','Visa','travel','intermediate'],
    ARRAY['die Reservierung','—','预订','Reservation','travel','intermediate'],
    ARRAY['die Reise','—','旅行','Journey','travel','beginner'],
    -- shopping
    ARRAY['der Preis','—','价格','Price','shopping','beginner'],
    ARRAY['der Rabatt','—','折扣','Discount','shopping','beginner'],
    ARRAY['der Kassenbon','—','收据','Receipt','shopping','beginner'],
    ARRAY['bezahlen','—','付款','To pay','shopping','beginner'],
    ARRAY['kaufen','—','买','To buy','shopping','beginner'],
    ARRAY['verkaufen','—','卖','To sell','shopping','intermediate'],
    ARRAY['teuer','—','贵','Expensive','shopping','beginner'],
    ARRAY['billig','—','便宜','Cheap','shopping','beginner'],
    ARRAY['das Geschäft','—','商店','Shop','shopping','beginner'],
    ARRAY['der Markt','—','市场','Market','shopping','beginner'],
    -- work
    ARRAY['die Arbeit','—','工作','Work','work','beginner'],
    ARRAY['das Büro','—','办公室','Office','work','beginner'],
    ARRAY['der Chef','—','老板','Boss','work','intermediate'],
    ARRAY['der Kollege','—','同事','Colleague','work','intermediate'],
    ARRAY['die Besprechung','—','会议','Meeting','work','intermediate'],
    ARRAY['der Bericht','—','报告','Report','work','intermediate'],
    ARRAY['das Gehalt','—','工资','Salary','work','intermediate'],
    ARRAY['die Überstunden','—','加班','Overtime','work','intermediate'],
    ARRAY['der Vertrag','—','合同','Contract','work','intermediate'],
    ARRAY['die Beförderung','—','升职','Promotion','work','intermediate'],
    ARRAY['kündigen','—','辞职','To resign','work','intermediate'],
    ARRAY['das Vorstellungsgespräch','—','面试','Job interview','work','intermediate'],
    ARRAY['das Projekt','—','项目','Project','work','intermediate'],
    ARRAY['die Frist','—','截止日期','Deadline','work','intermediate'],
    ARRAY['die Strategie','—','策略','Strategy','work','advanced'],
    -- health
    ARRAY['das Krankenhaus','—','医院','Hospital','health','beginner'],
    ARRAY['der Arzt','—','医生','Doctor','health','beginner'],
    ARRAY['das Medikament','—','药','Medicine','health','beginner'],
    ARRAY['die Erkältung','—','感冒','Cold','health','beginner'],
    ARRAY['das Fieber','—','发烧','Fever','health','beginner'],
    ARRAY['der Kopfschmerz','—','头痛','Headache','health','intermediate'],
    ARRAY['die Allergie','—','过敏','Allergy','health','intermediate'],
    ARRAY['die Operation','—','手术','Surgery','health','intermediate'],
    ARRAY['die Versicherung','—','保险','Insurance','health','intermediate'],
    ARRAY['das Rezept','—','处方','Prescription','health','intermediate'],
    -- tech/nature/emotion
    ARRAY['der Computer','—','电脑','Computer','tech','beginner'],
    ARRAY['das Smartphone','—','智能手机','Smartphone','tech','beginner'],
    ARRAY['das Internet','—','互联网','Internet','tech','beginner'],
    ARRAY['die App','—','应用程序','App','tech','beginner'],
    ARRAY['das Passwort','—','密码','Password','tech','beginner'],
    ARRAY['herunterladen','—','下载','To download','tech','intermediate'],
    ARRAY['die Cloud','—','云','Cloud','tech','intermediate'],
    ARRAY['künstliche Intelligenz','—','人工智能','AI','tech','intermediate'],
    ARRAY['die Software','—','软件','Software','tech','intermediate'],
    ARRAY['die Cybersicherheit','—','网络安全','Cybersecurity','tech','advanced'],
    ARRAY['der Berg','—','山','Mountain','nature','beginner'],
    ARRAY['der Fluss','—','河流','River','nature','beginner'],
    ARRAY['das Meer','—','海','Sea','nature','beginner'],
    ARRAY['der Wald','—','森林','Forest','nature','beginner'],
    ARRAY['die Sonne','—','太阳','Sun','nature','beginner'],
    ARRAY['das Wetter','—','天气','Weather','weather','beginner'],
    ARRAY['es ist heiß','—','热','It''s hot','weather','beginner'],
    ARRAY['es ist kalt','—','冷','It''s cold','weather','beginner'],
    ARRAY['es regnet','—','下雨','It''s raining','weather','beginner'],
    ARRAY['glücklich','—','高兴','Happy','emotion','beginner'],
    ARRAY['traurig','—','悲伤','Sad','emotion','beginner'],
    ARRAY['wütend','—','生气','Angry','emotion','beginner'],
    ARRAY['ängstlich','—','害怕','Scared','emotion','beginner'],
    ARRAY['die Liebe','—','爱','Love','emotion','beginner'],
    -- key verbs
    ARRAY['gehen','—','去/走','To go/walk','daily','beginner'],
    ARRAY['kommen','—','来','To come','daily','beginner'],
    ARRAY['machen','—','做','To do/make','daily','beginner'],
    ARRAY['haben','—','有','To have','daily','beginner'],
    ARRAY['sein','—','是/在','To be','daily','beginner'],
    ARRAY['werden','—','成为/将要','To become/will','daily','beginner'],
    ARRAY['wollen','—','想要','To want','daily','beginner'],
    ARRAY['können','—','能','To be able','daily','beginner'],
    ARRAY['müssen','—','必须','To must','daily','beginner'],
    ARRAY['wissen','—','知道','To know (fact)','daily','beginner'],
    ARRAY['kennen','—','认识','To know (person)','daily','beginner'],
    ARRAY['sehen','—','看','To see','daily','beginner'],
    ARRAY['sprechen','—','说话','To speak','daily','beginner'],
    ARRAY['hören','—','听','To hear/listen','daily','beginner'],
    ARRAY['lesen','—','读','To read','daily','beginner'],
    ARRAY['schreiben','—','写','To write','daily','beginner'],
    ARRAY['schlafen','—','睡觉','To sleep','daily','beginner'],
    ARRAY['fahren','—','开车/驾驶','To drive/travel','daily','beginner'],
    ARRAY['arbeiten','—','工作','To work','daily','beginner'],
    ARRAY['lernen','—','学习','To learn/study','daily','beginner'],
    ARRAY['verstehen','—','理解','To understand','daily','intermediate'],
    ARRAY['helfen','—','帮助','To help','daily','intermediate'],
    ARRAY['wählen','—','选择','To choose','daily','intermediate'],
    ARRAY['beginnen','—','开始','To begin','daily','intermediate'],
    ARRAY['beenden','—','结束','To finish/end','daily','intermediate'],
    ARRAY['antworten','—','回答','To answer','daily','intermediate'],
    ARRAY['fragen','—','问','To ask','daily','intermediate'],
    ARRAY['geben','—','给','To give','daily','beginner'],
    ARRAY['nehmen','—','拿/取','To take','daily','beginner'],
    ARRAY['finden','—','找到','To find','daily','intermediate'],
    -- advanced
    ARRAY['entwickeln','—','发展','To develop','work','advanced'],
    ARRAY['analysieren','—','分析','To analyse','work','advanced'],
    ARRAY['bewerten','—','评估','To evaluate','work','advanced'],
    ARRAY['verhandeln','—','谈判','To negotiate','work','advanced'],
    ARRAY['zusammenarbeiten','—','合作','To collaborate','work','advanced'],
    ARRAY['die Innovation','—','创新','Innovation','work','advanced'],
    ARRAY['die Nachhaltigkeit','—','可持续性','Sustainability','nature','advanced'],
    ARRAY['der Klimawandel','—','气候变化','Climate change','nature','advanced'],
    ARRAY['die Vielfalt','—','多样性','Diversity','study','advanced'],
    ARRAY['die Gerechtigkeit','—','公正','Justice/Fairness','study','advanced']
  ];
  i integer;
BEGIN
  FOR i IN 1..array_length(words, 1) LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index)
    VALUES ('de', words[i][1], words[i][2], words[i][3], words[i][4], words[i][5], words[i][6], i)
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;
