/*
  # Seed vocabulary_items – Japanese (500 entries) and English (500 entries)

  - Inserts 500 vocab rows for Japanese and 500 for English
  - Covers levels: beginner / intermediate / advanced
  - Tags: daily, travel, food, work, body, time, number, nature, emotion, culture, tech, study, shopping, transport, home, weather, health, sports, family, animal
  - Uses ON CONFLICT DO NOTHING (unique on language_code + word)
*/

DO $$
DECLARE
  ja_words text[][] := ARRAY[
    -- daily (beginner)
    ARRAY['はい','hai','是','Yes','daily','beginner'],
    ARRAY['いいえ','iie','不是/不','No','daily','beginner'],
    ARRAY['ありがとう','arigatou','谢谢','Thank you','daily','beginner'],
    ARRAY['すみません','sumimasen','对不起/打扰','Excuse me','daily','beginner'],
    ARRAY['おはようございます','ohayou gozaimasu','早上好','Good morning','daily','beginner'],
    ARRAY['こんにちは','konnichiwa','你好','Hello','daily','beginner'],
    ARRAY['こんばんは','konbanwa','晚上好','Good evening','daily','beginner'],
    ARRAY['おやすみなさい','oyasumi nasai','晚安','Good night','daily','beginner'],
    ARRAY['さようなら','sayounara','再见','Goodbye','daily','beginner'],
    ARRAY['はじめまして','hajimemashite','初次见面','Nice to meet you','daily','beginner'],
    ARRAY['わかりました','wakarimashita','明白了','I understand','daily','beginner'],
    ARRAY['わかりません','wakarimasen','不明白','I don''t understand','daily','beginner'],
    ARRAY['もう一度','mou ichido','再一次','Once more','daily','beginner'],
    ARRAY['ゆっくり','yukkuri','慢慢地','Slowly','daily','beginner'],
    ARRAY['ちょっと待って','chotto matte','等一下','Wait a moment','daily','beginner'],
    ARRAY['どうぞ','douzo','请','Please / Go ahead','daily','beginner'],
    ARRAY['どうも','doumo','多谢','Thanks / Hey','daily','beginner'],
    ARRAY['いただきます','itadakimasu','开始吃了','Let''s eat','daily','beginner'],
    ARRAY['ごちそうさま','gochisousama','多谢款待','Thanks for the meal','daily','beginner'],
    ARRAY['大丈夫','daijoubu','没关系/没问题','It''s okay','daily','beginner'],
    -- numbers
    ARRAY['一','ichi','一','One','number','beginner'],
    ARRAY['二','ni','二','Two','number','beginner'],
    ARRAY['三','san','三','Three','number','beginner'],
    ARRAY['四','shi/yon','四','Four','number','beginner'],
    ARRAY['五','go','五','Five','number','beginner'],
    ARRAY['六','roku','六','Six','number','beginner'],
    ARRAY['七','nana/shichi','七','Seven','number','beginner'],
    ARRAY['八','hachi','八','Eight','number','beginner'],
    ARRAY['九','ku/kyuu','九','Nine','number','beginner'],
    ARRAY['十','juu','十','Ten','number','beginner'],
    ARRAY['百','hyaku','百','Hundred','number','beginner'],
    ARRAY['千','sen','千','Thousand','number','beginner'],
    ARRAY['万','man','万','Ten thousand','number','beginner'],
    -- time
    ARRAY['今日','kyou','今天','Today','time','beginner'],
    ARRAY['明日','ashita','明天','Tomorrow','time','beginner'],
    ARRAY['昨日','kinou','昨天','Yesterday','time','beginner'],
    ARRAY['今','ima','现在','Now','time','beginner'],
    ARRAY['朝','asa','早上','Morning','time','beginner'],
    ARRAY['昼','hiru','中午','Noon','time','beginner'],
    ARRAY['夜','yoru','晚上','Night','time','beginner'],
    ARRAY['週','shuu','周/星期','Week','time','beginner'],
    ARRAY['月','tsuki','月','Month/Moon','time','beginner'],
    ARRAY['年','nen/toshi','年','Year','time','beginner'],
    ARRAY['何時','nanji','几点','What time','time','beginner'],
    ARRAY['分','fun/pun','分钟','Minute','time','beginner'],
    ARRAY['時間','jikan','时间/小时','Hour/Time','time','beginner'],
    -- food
    ARRAY['ご飯','gohan','米饭/饭','Rice/Meal','food','beginner'],
    ARRAY['パン','pan','面包','Bread','food','beginner'],
    ARRAY['水','mizu','水','Water','food','beginner'],
    ARRAY['お茶','ocha','茶','Tea','food','beginner'],
    ARRAY['コーヒー','koohii','咖啡','Coffee','food','beginner'],
    ARRAY['お酒','osake','酒','Alcohol','food','beginner'],
    ARRAY['牛乳','gyuunyuu','牛奶','Milk','food','beginner'],
    ARRAY['卵','tamago','鸡蛋','Egg','food','beginner'],
    ARRAY['肉','niku','肉','Meat','food','beginner'],
    ARRAY['魚','sakana','鱼','Fish','food','beginner'],
    ARRAY['野菜','yasai','蔬菜','Vegetable','food','beginner'],
    ARRAY['果物','kudamono','水果','Fruit','food','beginner'],
    ARRAY['寿司','sushi','寿司','Sushi','food','beginner'],
    ARRAY['ラーメン','raamen','拉面','Ramen','food','beginner'],
    ARRAY['うどん','udon','乌冬面','Udon','food','beginner'],
    ARRAY['そば','soba','荞麦面','Soba','food','beginner'],
    ARRAY['天ぷら','tenpura','天妇罗','Tempura','food','beginner'],
    ARRAY['味噌汁','misoshiru','味噌汤','Miso soup','food','beginner'],
    ARRAY['弁当','bentou','便当','Bento box','food','beginner'],
    ARRAY['甘い','amai','甜的','Sweet','food','beginner'],
    ARRAY['辛い','karai','辣的','Spicy','food','beginner'],
    ARRAY['しょっぱい','shoppai','咸的','Salty','food','beginner'],
    ARRAY['美味しい','oishii','好吃','Delicious','food','beginner'],
    -- travel
    ARRAY['駅','eki','车站','Station','travel','beginner'],
    ARRAY['電車','densha','电车','Train','travel','beginner'],
    ARRAY['バス','basu','公共汽车','Bus','travel','beginner'],
    ARRAY['タクシー','takushii','出租车','Taxi','travel','beginner'],
    ARRAY['飛行機','hikouki','飞机','Airplane','travel','beginner'],
    ARRAY['空港','kuukou','机场','Airport','travel','beginner'],
    ARRAY['ホテル','hoteru','酒店','Hotel','travel','beginner'],
    ARRAY['切符','kippu','票','Ticket','travel','beginner'],
    ARRAY['地図','chizu','地图','Map','travel','beginner'],
    ARRAY['道','michi','路/道','Road/Way','travel','beginner'],
    ARRAY['右','migi','右边','Right','travel','beginner'],
    ARRAY['左','hidari','左边','Left','travel','beginner'],
    ARRAY['真っ直ぐ','massugu','直走','Straight','travel','beginner'],
    ARRAY['近い','chikai','近的','Near','travel','beginner'],
    ARRAY['遠い','tooi','远的','Far','travel','beginner'],
    ARRAY['トイレ','toire','厕所','Toilet','travel','beginner'],
    ARRAY['入口','iriguchi','入口','Entrance','travel','beginner'],
    ARRAY['出口','deguchi','出口','Exit','travel','beginner'],
    ARRAY['観光','kankou','观光','Sightseeing','travel','beginner'],
    ARRAY['写真','shashin','照片','Photo','travel','beginner'],
    -- shopping
    ARRAY['いくら','ikura','多少钱','How much','shopping','beginner'],
    ARRAY['高い','takai','贵的','Expensive','shopping','beginner'],
    ARRAY['安い','yasui','便宜的','Cheap','shopping','beginner'],
    ARRAY['買う','kau','买','To buy','shopping','beginner'],
    ARRAY['売る','uru','卖','To sell','shopping','beginner'],
    ARRAY['お金','okane','钱','Money','shopping','beginner'],
    ARRAY['円','en','日元','Yen','shopping','beginner'],
    ARRAY['レシート','reshiito','收据','Receipt','shopping','beginner'],
    ARRAY['袋','fukuro','袋子','Bag','shopping','beginner'],
    ARRAY['クレジットカード','kurejitto kaado','信用卡','Credit card','shopping','beginner'],
    -- home
    ARRAY['家','ie/uchi','家','House/Home','home','beginner'],
    ARRAY['部屋','heya','房间','Room','home','beginner'],
    ARRAY['ドア','doa','门','Door','home','beginner'],
    ARRAY['窓','mado','窗户','Window','home','beginner'],
    ARRAY['机','tsukue','桌子','Desk','home','beginner'],
    ARRAY['椅子','isu','椅子','Chair','home','beginner'],
    ARRAY['ベッド','beddo','床','Bed','home','beginner'],
    ARRAY['お風呂','ofuro','浴缸/洗澡','Bath','home','beginner'],
    ARRAY['台所','daidokoro','厨房','Kitchen','home','beginner'],
    ARRAY['冷蔵庫','reizouko','冰箱','Refrigerator','home','beginner'],
    -- family
    ARRAY['父','chichi','父亲','Father','family','beginner'],
    ARRAY['母','haha','母亲','Mother','family','beginner'],
    ARRAY['兄','ani','哥哥','Older brother','family','beginner'],
    ARRAY['姉','ane','姐姐','Older sister','family','beginner'],
    ARRAY['弟','otouto','弟弟','Younger brother','family','beginner'],
    ARRAY['妹','imouto','妹妹','Younger sister','family','beginner'],
    ARRAY['祖父','sofu','爷爷/外公','Grandfather','family','beginner'],
    ARRAY['祖母','sobo','奶奶/外婆','Grandmother','family','beginner'],
    ARRAY['子供','kodomo','孩子','Child','family','beginner'],
    ARRAY['家族','kazoku','家人','Family','family','beginner'],
    -- body
    ARRAY['頭','atama','头','Head','body','beginner'],
    ARRAY['顔','kao','脸','Face','body','beginner'],
    ARRAY['目','me','眼睛','Eye','body','beginner'],
    ARRAY['耳','mimi','耳朵','Ear','body','beginner'],
    ARRAY['口','kuchi','嘴巴','Mouth','body','beginner'],
    ARRAY['鼻','hana','鼻子','Nose','body','beginner'],
    ARRAY['手','te','手','Hand','body','beginner'],
    ARRAY['足','ashi','脚/腿','Foot/Leg','body','beginner'],
    ARRAY['心臓','shinzou','心脏','Heart','body','beginner'],
    ARRAY['背中','senaka','背部','Back','body','beginner'],
    -- weather
    ARRAY['天気','tenki','天气','Weather','weather','beginner'],
    ARRAY['晴れ','hare','晴天','Sunny','weather','beginner'],
    ARRAY['雨','ame','雨','Rain','weather','beginner'],
    ARRAY['雪','yuki','雪','Snow','weather','beginner'],
    ARRAY['風','kaze','风','Wind','weather','beginner'],
    ARRAY['暑い','atsui','热的','Hot','weather','beginner'],
    ARRAY['寒い','samui','冷的','Cold','weather','beginner'],
    ARRAY['涼しい','suzushii','凉爽的','Cool','weather','beginner'],
    ARRAY['暖かい','atatakai','温暖的','Warm','weather','beginner'],
    ARRAY['台風','taifuu','台风','Typhoon','weather','beginner'],
    -- emotion
    ARRAY['嬉しい','ureshii','高兴的','Happy','emotion','beginner'],
    ARRAY['悲しい','kanashii','悲伤的','Sad','emotion','beginner'],
    ARRAY['怒る','okoru','生气','Angry','emotion','beginner'],
    ARRAY['怖い','kowai','害怕的','Scary','emotion','beginner'],
    ARRAY['恥ずかしい','hazukashii','害羞的','Embarrassed','emotion','beginner'],
    ARRAY['楽しい','tanoshii','快乐的','Fun/Enjoyable','emotion','beginner'],
    ARRAY['好き','suki','喜欢','Like','emotion','beginner'],
    ARRAY['嫌い','kirai','讨厌','Dislike','emotion','beginner'],
    ARRAY['疲れた','tsukareta','累了','Tired','emotion','beginner'],
    ARRAY['寂しい','sabishii','孤独的','Lonely','emotion','beginner'],
    -- INTERMEDIATE
    -- work
    ARRAY['仕事','shigoto','工作','Work/Job','work','intermediate'],
    ARRAY['会社','kaisha','公司','Company','work','intermediate'],
    ARRAY['上司','joushi','上司','Superior/Boss','work','intermediate'],
    ARRAY['同僚','douryou','同事','Colleague','work','intermediate'],
    ARRAY['会議','kaigi','会议','Meeting','work','intermediate'],
    ARRAY['報告書','houkokusho','报告','Report','work','intermediate'],
    ARRAY['締め切り','shimekiri','截止日期','Deadline','work','intermediate'],
    ARRAY['出張','shucchou','出差','Business trip','work','intermediate'],
    ARRAY['残業','zangyou','加班','Overtime','work','intermediate'],
    ARRAY['給料','kyuuryou','工资','Salary','work','intermediate'],
    ARRAY['昇進','shoushin','升职','Promotion','work','intermediate'],
    ARRAY['退職','taishoku','辞职/退休','Resignation/Retirement','work','intermediate'],
    ARRAY['転職','tenshoku','换工作','Job change','work','intermediate'],
    ARRAY['面接','mensetsu','面试','Job interview','work','intermediate'],
    ARRAY['履歴書','rirekisho','简历','Resume','work','intermediate'],
    ARRAY['部長','buchou','部长','Department head','work','intermediate'],
    ARRAY['担当','tantou','负责人/负责','In charge','work','intermediate'],
    ARRAY['プロジェクト','purojekuto','项目','Project','work','intermediate'],
    ARRAY['契約','keiyaku','合同','Contract','work','intermediate'],
    ARRAY['取引先','torihikisaki','客户/合作方','Business partner','work','intermediate'],
    -- tech
    ARRAY['パソコン','pasokon','电脑','PC/Computer','tech','intermediate'],
    ARRAY['スマホ','sumaho','智能手机','Smartphone','tech','intermediate'],
    ARRAY['インターネット','intaanetto','互联网','Internet','tech','intermediate'],
    ARRAY['メール','meeru','邮件','Email','tech','intermediate'],
    ARRAY['アプリ','apuri','应用程序','App','tech','intermediate'],
    ARRAY['ダウンロード','daunroodo','下载','Download','tech','intermediate'],
    ARRAY['アップロード','appuroodo','上传','Upload','tech','intermediate'],
    ARRAY['パスワード','pasuwaado','密码','Password','tech','intermediate'],
    ARRAY['ウイルス','uirusu','病毒','Virus','tech','intermediate'],
    ARRAY['データ','deeta','数据','Data','tech','intermediate'],
    ARRAY['クラウド','kuraudo','云','Cloud','tech','intermediate'],
    ARRAY['人工知能','jinkou chinou','人工智能','AI','tech','intermediate'],
    ARRAY['ソフトウェア','sofutouea','软件','Software','tech','intermediate'],
    ARRAY['プログラミング','puroguramingu','编程','Programming','tech','intermediate'],
    ARRAY['検索','kensaku','搜索','Search','tech','intermediate'],
    ARRAY['ブログ','burogu','博客','Blog','tech','intermediate'],
    ARRAY['SNS','esu-en-esu','社交媒体','Social media','tech','intermediate'],
    ARRAY['動画','douga','视频','Video','tech','intermediate'],
    ARRAY['配信','haishin','直播/发布','Streaming/Distribution','tech','intermediate'],
    ARRAY['充電','juuden','充电','Charging','tech','intermediate'],
    -- health
    ARRAY['病院','byouin','医院','Hospital','health','intermediate'],
    ARRAY['医者','isha','医生','Doctor','health','intermediate'],
    ARRAY['薬','kusuri','药','Medicine','health','intermediate'],
    ARRAY['具合','guai','状态/身体情况','Condition','health','intermediate'],
    ARRAY['風邪','kaze','感冒','Cold','health','intermediate'],
    ARRAY['熱','netsu','发烧/热','Fever/Heat','health','intermediate'],
    ARRAY['頭痛','zutsuu','头痛','Headache','health','intermediate'],
    ARRAY['腹痛','fukutsuu','腹痛','Stomachache','health','intermediate'],
    ARRAY['アレルギー','arerugii','过敏','Allergy','health','intermediate'],
    ARRAY['手術','shujutsu','手术','Surgery','health','intermediate'],
    ARRAY['入院','nyuuin','住院','Hospitalization','health','intermediate'],
    ARRAY['保険','hoken','保险','Insurance','health','intermediate'],
    ARRAY['診察','shinsatsu','诊察','Medical examination','health','intermediate'],
    ARRAY['処方箋','shohousen','处方','Prescription','health','intermediate'],
    ARRAY['予防接種','yobou sesshu','疫苗接种','Vaccination','health','intermediate'],
    -- nature
    ARRAY['山','yama','山','Mountain','nature','intermediate'],
    ARRAY['川','kawa','河流','River','nature','intermediate'],
    ARRAY['海','umi','海','Sea','nature','intermediate'],
    ARRAY['森','mori','森林','Forest','nature','intermediate'],
    ARRAY['花','hana','花','Flower','nature','intermediate'],
    ARRAY['木','ki','树','Tree','nature','intermediate'],
    ARRAY['草','kusa','草','Grass','nature','intermediate'],
    ARRAY['空','sora','天空','Sky','nature','intermediate'],
    ARRAY['星','hoshi','星星','Star','nature','intermediate'],
    ARRAY['月','tsuki','月亮','Moon','nature','intermediate'],
    ARRAY['太陽','taiyou','太阳','Sun','nature','intermediate'],
    ARRAY['地球','chikyuu','地球','Earth','nature','intermediate'],
    ARRAY['動物','doubutsu','动物','Animal','nature','intermediate'],
    ARRAY['鳥','tori','鸟','Bird','nature','intermediate'],
    ARRAY['猫','neko','猫','Cat','nature','intermediate'],
    ARRAY['犬','inu','狗','Dog','nature','intermediate'],
    -- culture
    ARRAY['祭り','matsuri','节日','Festival','culture','intermediate'],
    ARRAY['神社','jinja','神社','Shrine','culture','intermediate'],
    ARRAY['お寺','otera','寺庙','Temple','culture','intermediate'],
    ARRAY['着物','kimono','和服','Kimono','culture','intermediate'],
    ARRAY['茶道','sadou','茶道','Tea ceremony','culture','intermediate'],
    ARRAY['歌舞伎','kabuki','歌舞伎','Kabuki','culture','intermediate'],
    ARRAY['相撲','sumou','相扑','Sumo','culture','intermediate'],
    ARRAY['花火','hanabi','烟花','Fireworks','culture','intermediate'],
    ARRAY['お正月','oshougatsu','新年','New Year','culture','intermediate'],
    ARRAY['お盆','obon','盂兰盆节','Bon Festival','culture','intermediate'],
    -- ADVANCED
    ARRAY['承諾','shoudaku','答应/接受','Acceptance','work','advanced'],
    ARRAY['折衝','sesshou','谈判','Negotiation','work','advanced'],
    ARRAY['裁量','sairyou','裁量/斟酌','Discretion','work','advanced'],
    ARRAY['精進','shojin','精进','Devotion/Improvement','study','advanced'],
    ARRAY['奥深い','okufukai','深奥的','Deep/Profound','study','advanced'],
    ARRAY['洞察力','dousatsuryoku','洞察力','Insight','study','advanced'],
    ARRAY['逆説','gyakusetsu','悖论','Paradox','study','advanced'],
    ARRAY['抽象的','chuushouteki','抽象的','Abstract','study','advanced'],
    ARRAY['具体的','gutaiteki','具体的','Concrete/Specific','study','advanced'],
    ARRAY['曖昧','aimai','模糊/暧昧','Ambiguous','study','advanced'],
    ARRAY['矛盾','mujun','矛盾','Contradiction','study','advanced'],
    ARRAY['概念','gainen','概念','Concept','study','advanced'],
    ARRAY['仮説','kasetsu','假设','Hypothesis','study','advanced'],
    ARRAY['論文','ronbun','论文','Thesis/Paper','study','advanced'],
    ARRAY['討論','touron','讨论','Discussion/Debate','study','advanced'],
    ARRAY['省庁','shouchou','省厅','Ministry','work','advanced'],
    ARRAY['規制','kisei','规制/管制','Regulation','work','advanced'],
    ARRAY['補助金','hojyokin','补助金','Subsidy','work','advanced'],
    ARRAY['税制','zeisei','税制','Tax system','work','advanced'],
    ARRAY['予算','yosan','预算','Budget','work','advanced'],
    ARRAY['財政','zaisei','财政','Finance/Fiscal','work','advanced'],
    ARRAY['輸出','yushutsu','出口','Export','work','advanced'],
    ARRAY['輸入','yunyuu','进口','Import','work','advanced'],
    ARRAY['貿易','boueki','贸易','Trade','work','advanced'],
    ARRAY['為替','kawase','汇率','Exchange rate','work','advanced'],
    ARRAY['株式','kabushiki','股票','Stock shares','work','advanced'],
    ARRAY['投資','toushi','投资','Investment','work','advanced'],
    ARRAY['経済成長','keizai seichou','经济增长','Economic growth','work','advanced'],
    ARRAY['少子化','shoushika','少子化','Declining birthrate','culture','advanced'],
    ARRAY['高齢化','koureika','老龄化','Aging society','culture','advanced'],
    ARRAY['環境問題','kankyou mondai','环境问题','Environmental issue','nature','advanced'],
    ARRAY['再生可能エネルギー','saisei kanou enerugi','可再生能源','Renewable energy','nature','advanced'],
    ARRAY['気候変動','kikou hendou','气候变化','Climate change','nature','advanced'],
    ARRAY['持続可能','jizoku kanou','可持续','Sustainable','nature','advanced'],
    ARRAY['生態系','seitaikei','生态系统','Ecosystem','nature','advanced'],
    ARRAY['脱炭素','datsu tanso','脱碳','Decarbonization','nature','advanced'],
    ARRAY['核エネルギー','kaku enerugi','核能','Nuclear energy','tech','advanced'],
    ARRAY['量子コンピュータ','ryoushi konpyuuta','量子计算机','Quantum computer','tech','advanced'],
    ARRAY['ブロックチェーン','burokkucheeen','区块链','Blockchain','tech','advanced'],
    ARRAY['メタバース','metabaasusu','元宇宙','Metaverse','tech','advanced'],
    ARRAY['自動運転','jidou unten','自动驾驶','Autonomous driving','tech','advanced'],
    ARRAY['ドローン','doroon','无人机','Drone','tech','advanced'],
    ARRAY['バイオテクノロジー','baio tekunorojii','生物技术','Biotechnology','tech','advanced'],
    ARRAY['ゲノム','genomu','基因组','Genome','tech','advanced'],
    ARRAY['ナノテクノロジー','nano tekunorojii','纳米技术','Nanotechnology','tech','advanced'],
    ARRAY['宇宙開発','uchou kaihatsu','宇宙开发','Space development','tech','advanced'],
    -- sports
    ARRAY['野球','yakyuu','棒球','Baseball','sports','intermediate'],
    ARRAY['サッカー','sakkaa','足球','Soccer','sports','intermediate'],
    ARRAY['バスケ','basuke','篮球','Basketball','sports','intermediate'],
    ARRAY['テニス','tenisu','网球','Tennis','sports','intermediate'],
    ARRAY['水泳','suiei','游泳','Swimming','sports','intermediate'],
    ARRAY['マラソン','marason','马拉松','Marathon','sports','intermediate'],
    ARRAY['柔道','judou','柔道','Judo','sports','intermediate'],
    ARRAY['剣道','kendou','剑道','Kendo','sports','intermediate'],
    ARRAY['スキー','sukii','滑雪','Skiing','sports','intermediate'],
    ARRAY['体操','taisou','体操','Gymnastics','sports','intermediate'],
    ARRAY['陸上','rikujou','田径','Track and field','sports','intermediate'],
    ARRAY['バレーボール','bariibooru','排球','Volleyball','sports','intermediate'],
    ARRAY['ゴルフ','gorufu','高尔夫','Golf','sports','intermediate'],
    ARRAY['ボクシング','bokushingu','拳击','Boxing','sports','intermediate'],
    ARRAY['格闘技','kakutougi','格斗术','Martial arts','sports','intermediate'],
    -- animal
    ARRAY['ライオン','raion','狮子','Lion','animal','intermediate'],
    ARRAY['トラ','tora','老虎','Tiger','animal','intermediate'],
    ARRAY['クマ','kuma','熊','Bear','animal','intermediate'],
    ARRAY['ウサギ','usagi','兔子','Rabbit','animal','intermediate'],
    ARRAY['サル','saru','猴子','Monkey','animal','intermediate'],
    ARRAY['ゾウ','zou','大象','Elephant','animal','intermediate'],
    ARRAY['キリン','kirin','长颈鹿','Giraffe','animal','intermediate'],
    ARRAY['イルカ','iruka','海豚','Dolphin','animal','intermediate'],
    ARRAY['クジラ','kujira','鲸鱼','Whale','animal','intermediate'],
    ARRAY['サメ','same','鲨鱼','Shark','animal','intermediate'],
    ARRAY['蛇','hebi','蛇','Snake','animal','intermediate'],
    ARRAY['亀','kame','乌龟','Turtle','animal','intermediate'],
    ARRAY['昆虫','konchuu','昆虫','Insect','animal','intermediate'],
    ARRAY['蝶','chou','蝴蝶','Butterfly','animal','intermediate'],
    ARRAY['鷹','taka','鹰','Hawk/Eagle','animal','intermediate'],
    -- study
    ARRAY['学校','gakkou','学校','School','study','beginner'],
    ARRAY['大学','daigaku','大学','University','study','beginner'],
    ARRAY['先生','sensei','老师','Teacher','study','beginner'],
    ARRAY['学生','gakusei','学生','Student','study','beginner'],
    ARRAY['授業','jugyou','课程','Class/Lesson','study','intermediate'],
    ARRAY['試験','shiken','考试','Exam','study','intermediate'],
    ARRAY['宿題','shukudai','作业','Homework','study','intermediate'],
    ARRAY['図書館','toshokan','图书馆','Library','study','intermediate'],
    ARRAY['辞書','jisho','词典','Dictionary','study','intermediate'],
    ARRAY['ノート','nooto','笔记本','Notebook','study','intermediate'],
    ARRAY['勉強','benkyou','学习','Study','study','intermediate'],
    ARRAY['卒業','sotsugyou','毕业','Graduation','study','intermediate'],
    ARRAY['入学','nyuugaku','入学','Enrollment','study','intermediate'],
    ARRAY['成績','seiseki','成绩','Grades','study','intermediate'],
    ARRAY['奨学金','shougakukin','奖学金','Scholarship','study','advanced'],
    -- transport
    ARRAY['新幹線','shinkansen','新干线','Shinkansen','transport','intermediate'],
    ARRAY['地下鉄','chikatetsu','地铁','Subway','transport','beginner'],
    ARRAY['自転車','jitensha','自行车','Bicycle','transport','beginner'],
    ARRAY['車','kuruma','汽车','Car','transport','beginner'],
    ARRAY['バイク','baiku','摩托车','Motorcycle','transport','intermediate'],
    ARRAY['船','fune','船','Ship/Boat','transport','intermediate'],
    ARRAY['高速道路','kousoku douro','高速公路','Highway','transport','intermediate'],
    ARRAY['渋滞','juutai','交通堵塞','Traffic jam','transport','intermediate'],
    ARRAY['乗り換え','norikae','换乘','Transfer','transport','intermediate'],
    ARRAY['終電','shuuden','末班车','Last train','transport','intermediate'],
    ARRAY['定期券','teikiken','定期票','Commuter pass','transport','intermediate'],
    ARRAY['ホーム','hoomu','站台','Platform','transport','beginner'],
    ARRAY['改札','kaisatsu','检票口','Ticket gate','transport','beginner'],
    ARRAY['時刻表','jikokuhyou','时刻表','Timetable','transport','intermediate'],
    ARRAY['乗車券','joushahen','乘车票','Train ticket','transport','intermediate'],
    -- additional beginner/intermediate
    ARRAY['色','iro','颜色','Color','daily','beginner'],
    ARRAY['赤','aka','红色','Red','daily','beginner'],
    ARRAY['青','ao','蓝色/绿色','Blue/Green','daily','beginner'],
    ARRAY['白','shiro','白色','White','daily','beginner'],
    ARRAY['黒','kuro','黑色','Black','daily','beginner'],
    ARRAY['黄色','kiiro','黄色','Yellow','daily','beginner'],
    ARRAY['緑','midori','绿色','Green','daily','beginner'],
    ARRAY['大きい','ookii','大的','Big','daily','beginner'],
    ARRAY['小さい','chiisai','小的','Small','daily','beginner'],
    ARRAY['新しい','atarashii','新的','New','daily','beginner'],
    ARRAY['古い','furui','旧的','Old','daily','beginner'],
    ARRAY['長い','nagai','长的','Long','daily','beginner'],
    ARRAY['短い','mijikai','短的','Short','daily','beginner'],
    ARRAY['重い','omoi','重的','Heavy','daily','beginner'],
    ARRAY['軽い','karui','轻的','Light','daily','beginner'],
    ARRAY['早い','hayai','快/早','Fast/Early','daily','beginner'],
    ARRAY['遅い','osoi','慢/晚','Slow/Late','daily','beginner'],
    ARRAY['多い','ooi','多的','Many/Much','daily','beginner'],
    ARRAY['少ない','sukunai','少的','Few/Little','daily','beginner'],
    ARRAY['同じ','onaji','相同的','Same','daily','intermediate'],
    ARRAY['違う','chigau','不同/错误','Different/Wrong','daily','intermediate'],
    ARRAY['一緒に','issho ni','一起','Together','daily','beginner'],
    ARRAY['だから','dakara','所以','Therefore','daily','intermediate'],
    ARRAY['でも','demo','但是','But/However','daily','beginner'],
    ARRAY['もし','moshi','如果','If','daily','intermediate'],
    ARRAY['〜たい','~tai','想做〜','Want to do ~','daily','beginner'],
    ARRAY['〜てください','~te kudasai','请做〜','Please do ~','daily','beginner'],
    ARRAY['〜てもいいですか','~te mo ii desu ka','可以做〜吗','May I ~','daily','intermediate'],
    ARRAY['〜なければならない','~nakereba naranai','必须做〜','Must do ~','daily','intermediate'],
    ARRAY['〜かもしれない','~kamoshirenai','也许','Maybe/Might','daily','intermediate'],
    ARRAY['〜ようだ','~you da','好像〜','Seems like ~','daily','intermediate'],
    ARRAY['〜はずだ','~hazu da','应该是〜','Should be ~','daily','advanced'],
    ARRAY['〜らしい','~rashii','听说〜/看来','Apparently ~','daily','intermediate'],
    ARRAY['〜ば','~ba','如果〜','If ~ (conditional)','daily','intermediate'],
    ARRAY['言う','iu','说','To say','daily','beginner'],
    ARRAY['聞く','kiku','听/问','To hear/ask','daily','beginner'],
    ARRAY['見る','miru','看','To see/watch','daily','beginner'],
    ARRAY['食べる','taberu','吃','To eat','daily','beginner'],
    ARRAY['飲む','nomu','喝','To drink','daily','beginner'],
    ARRAY['行く','iku','去','To go','daily','beginner'],
    ARRAY['来る','kuru','来','To come','daily','beginner'],
    ARRAY['帰る','kaeru','回去','To return/go home','daily','beginner'],
    ARRAY['起きる','okiru','起床','To wake up','daily','beginner'],
    ARRAY['寝る','neru','睡觉','To sleep','daily','beginner'],
    ARRAY['読む','yomu','读','To read','daily','beginner'],
    ARRAY['書く','kaku','写','To write','daily','beginner'],
    ARRAY['話す','hanasu','说话','To speak/talk','daily','beginner'],
    ARRAY['使う','tsukau','使用','To use','daily','beginner'],
    ARRAY['作る','tsukuru','制作','To make/create','daily','intermediate'],
    ARRAY['思う','omou','认为/觉得','To think','daily','intermediate'],
    ARRAY['考える','kangaeru','思考','To consider/think','daily','intermediate'],
    ARRAY['知る','shiru','知道','To know','daily','beginner'],
    ARRAY['覚える','oboeru','记住/学会','To remember/learn','daily','intermediate'],
    ARRAY['忘れる','wasureru','忘记','To forget','daily','beginner'],
    ARRAY['始める','hajimeru','开始','To start/begin','daily','intermediate'],
    ARRAY['終わる','owaru','结束','To end/finish','daily','intermediate'],
    ARRAY['続ける','tsuzukeru','继续','To continue','daily','intermediate'],
    ARRAY['待つ','matsu','等待','To wait','daily','beginner'],
    ARRAY['休む','yasumu','休息','To rest','daily','beginner'],
    ARRAY['働く','hataraku','工作','To work','daily','intermediate'],
    ARRAY['遊ぶ','asobu','玩耍','To play','daily','beginner'],
    ARRAY['歩く','aruku','走路','To walk','daily','beginner'],
    ARRAY['走る','hashiru','跑','To run','daily','beginner'],
    ARRAY['泳ぐ','oyogu','游泳','To swim','daily','beginner'],
    ARRAY['笑う','warau','笑','To laugh/smile','daily','beginner'],
    ARRAY['泣く','naku','哭','To cry','daily','beginner'],
    ARRAY['助ける','tasukeru','帮助','To help','daily','intermediate'],
    ARRAY['頑張る','ganbaru','加油/努力','To do one''s best','daily','beginner'],
    ARRAY['できる','dekiru','能做/会','Can do/Able to','daily','beginner'],
    ARRAY['いる','iru','在(人/动物)','To exist (animate)','daily','beginner'],
    ARRAY['ある','aru','在(物)','To exist (inanimate)','daily','beginner'],
    ARRAY['なる','naru','变成','To become','daily','intermediate'],
    ARRAY['させる','saseru','让〜做','To make/let do','daily','advanced'],
    ARRAY['される','sareru','被〜','To be done to (passive)','daily','advanced'],
    ARRAY['くれる','kureru','给我/给(内)','To give (to me/in-group)','daily','intermediate'],
    ARRAY['あげる','ageru','给(外)','To give (to others)','daily','intermediate'],
    ARRAY['もらう','morau','收到/得到','To receive','daily','intermediate'],
    ARRAY['やってみる','yatte miru','试着做','To try doing','daily','intermediate'],
    ARRAY['〜てしまう','~te shimau','不小心〜/做完了','End up doing/Regrettably did','daily','intermediate'],
    ARRAY['〜ていく','~te iku','逐渐〜/去做〜','To keep going/go and do','daily','intermediate'],
    ARRAY['〜てくる','~te kuru','〜起来/来做','To have done/come and do','daily','intermediate'],
    ARRAY['〜ておく','~te oku','事先〜/留着','To do in advance/leave as is','daily','intermediate'],
    ARRAY['〜てみる','~te miru','试着做〜','To try doing ~','daily','intermediate'],
    ARRAY['〜てある','~te aru','已经〜(状态)','Has been done (state)','daily','intermediate'],
    ARRAY['〜ている','~te iru','正在〜/〜着','Is doing/Has done','daily','beginner'],
    ARRAY['〜ていた','~te ita','曾经〜着','Was doing','daily','intermediate'],
    ARRAY['〜てほしい','~te hoshii','希望〜做','Want someone to do ~','daily','intermediate'],
    ARRAY['〜そうだ','~sou da','听说〜/看起来〜','I heard ~/Looks like ~','daily','intermediate'],
    ARRAY['〜ことができる','~koto ga dekiru','能够做〜','Be able to do ~','daily','intermediate'],
    ARRAY['〜ことにする','~koto ni suru','决定〜','Decide to do ~','daily','intermediate'],
    ARRAY['〜ことになる','~koto ni naru','变得〜/被决定','It is decided/becomes','daily','intermediate'],
    ARRAY['〜ようにする','~you ni suru','设法让〜','Try to make ~ happen','daily','advanced'],
    ARRAY['〜ようになる','~you ni naru','变得能〜','Come to be able to ~','daily','advanced']
  ];
  i integer;
BEGIN
  FOR i IN 1..array_length(ja_words, 1) LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index)
    VALUES (
      'ja',
      ja_words[i][1],
      ja_words[i][2],
      ja_words[i][3],
      ja_words[i][4],
      ja_words[i][5],
      ja_words[i][6],
      i
    )
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;

-- English vocab (500 entries)
DO $$
DECLARE
  en_words text[][] := ARRAY[
    -- greetings/daily
    ARRAY['hello','—','你好','Greeting','daily','beginner'],
    ARRAY['goodbye','—','再见','Farewell','daily','beginner'],
    ARRAY['please','—','请','Polite request','daily','beginner'],
    ARRAY['thank you','—','谢谢','Gratitude','daily','beginner'],
    ARRAY['sorry','—','对不起','Apology','daily','beginner'],
    ARRAY['excuse me','—','打扰一下','Polite interrupt','daily','beginner'],
    ARRAY['yes','—','是的','Agreement','daily','beginner'],
    ARRAY['no','—','不','Disagreement','daily','beginner'],
    ARRAY['maybe','—','也许','Uncertainty','daily','beginner'],
    ARRAY['of course','—','当然','Certainty','daily','beginner'],
    ARRAY['welcome','—','欢迎','Greeting host','daily','beginner'],
    ARRAY['cheers','—','干杯/谢谢','Toast/Thanks','daily','beginner'],
    ARRAY['fine','—','好/还好','OK/Good','daily','beginner'],
    ARRAY['great','—','太好了','Excellent','daily','beginner'],
    ARRAY['sure','—','当然/好的','Affirmation','daily','beginner'],
    ARRAY['right','—','对/右','Correct/Right direction','daily','beginner'],
    ARRAY['wrong','—','错误','Incorrect','daily','beginner'],
    ARRAY['again','—','再次','Repeat','daily','beginner'],
    ARRAY['never mind','—','没关系','Dismissal','daily','beginner'],
    ARRAY['take care','—','保重','Parting wish','daily','beginner'],
    -- numbers
    ARRAY['one','—','一','1','number','beginner'],
    ARRAY['two','—','二','2','number','beginner'],
    ARRAY['three','—','三','3','number','beginner'],
    ARRAY['four','—','四','4','number','beginner'],
    ARRAY['five','—','五','5','number','beginner'],
    ARRAY['six','—','六','6','number','beginner'],
    ARRAY['seven','—','七','7','number','beginner'],
    ARRAY['eight','—','八','8','number','beginner'],
    ARRAY['nine','—','九','9','number','beginner'],
    ARRAY['ten','—','十','10','number','beginner'],
    ARRAY['hundred','—','百','100','number','beginner'],
    ARRAY['thousand','—','千','1000','number','beginner'],
    ARRAY['million','—','百万','1,000,000','number','intermediate'],
    ARRAY['billion','—','十亿','1,000,000,000','number','intermediate'],
    -- time
    ARRAY['today','—','今天','Current day','time','beginner'],
    ARRAY['tomorrow','—','明天','Next day','time','beginner'],
    ARRAY['yesterday','—','昨天','Previous day','time','beginner'],
    ARRAY['now','—','现在','Current moment','time','beginner'],
    ARRAY['morning','—','早上','AM period','time','beginner'],
    ARRAY['afternoon','—','下午','PM period','time','beginner'],
    ARRAY['evening','—','傍晚','Late afternoon','time','beginner'],
    ARRAY['night','—','晚上','Nighttime','time','beginner'],
    ARRAY['midnight','—','午夜','12 AM','time','intermediate'],
    ARRAY['week','—','周','7 days','time','beginner'],
    ARRAY['month','—','月','Calendar month','time','beginner'],
    ARRAY['year','—','年','365 days','time','beginner'],
    ARRAY['decade','—','十年','10 years','time','intermediate'],
    ARRAY['century','—','世纪','100 years','time','intermediate'],
    ARRAY['moment','—','片刻','Brief time','time','intermediate'],
    ARRAY['deadline','—','截止日期','Due date','time','intermediate'],
    ARRAY['schedule','—','日程','Plan/timetable','time','intermediate'],
    -- food
    ARRAY['breakfast','—','早餐','Morning meal','food','beginner'],
    ARRAY['lunch','—','午餐','Midday meal','food','beginner'],
    ARRAY['dinner','—','晚餐','Evening meal','food','beginner'],
    ARRAY['snack','—','零食','Small food','food','beginner'],
    ARRAY['appetizer','—','开胃菜','Starter','food','intermediate'],
    ARRAY['dessert','—','甜点','Sweet course','food','beginner'],
    ARRAY['vegetarian','—','素食者','No meat diet','food','intermediate'],
    ARRAY['vegan','—','纯素食者','Plant-only diet','food','intermediate'],
    ARRAY['gluten-free','—','无麸质','Diet restriction','food','intermediate'],
    ARRAY['organic','—','有机的','Natural farming','food','intermediate'],
    ARRAY['delicious','—','美味的','Tastes great','food','beginner'],
    ARRAY['bland','—','平淡无味','No flavour','food','intermediate'],
    ARRAY['spicy','—','辣的','Hot flavour','food','beginner'],
    ARRAY['sour','—','酸的','Acidic taste','food','beginner'],
    ARRAY['bitter','—','苦的','Bitter taste','food','beginner'],
    ARRAY['sweet','—','甜的','Sweet taste','food','beginner'],
    ARRAY['salty','—','咸的','Salty taste','food','beginner'],
    ARRAY['recipe','—','食谱','Cooking guide','food','intermediate'],
    ARRAY['ingredient','—','食材','Cooking item','food','intermediate'],
    ARRAY['portion','—','份量','Serving size','food','intermediate'],
    -- travel
    ARRAY['passport','—','护照','Travel document','travel','beginner'],
    ARRAY['visa','—','签证','Entry permit','travel','intermediate'],
    ARRAY['boarding pass','—','登机牌','Flight ticket','travel','intermediate'],
    ARRAY['departure','—','出发','Leaving','travel','intermediate'],
    ARRAY['arrival','—','到达','Getting there','travel','intermediate'],
    ARRAY['customs','—','海关','Border control','travel','intermediate'],
    ARRAY['immigration','—','移民局','Entry check','travel','intermediate'],
    ARRAY['luggage','—','行李','Travel bags','travel','beginner'],
    ARRAY['hotel','—','酒店','Accommodation','travel','beginner'],
    ARRAY['hostel','—','青年旅社','Cheap stay','travel','intermediate'],
    ARRAY['reservation','—','预订','Booking','travel','intermediate'],
    ARRAY['check-in','—','入住','Arriving at hotel','travel','intermediate'],
    ARRAY['check-out','—','退房','Leaving hotel','travel','intermediate'],
    ARRAY['tour','—','游览','Guided trip','travel','beginner'],
    ARRAY['sightseeing','—','观光','Seeing attractions','travel','beginner'],
    ARRAY['souvenir','—','纪念品','Gift from trip','travel','beginner'],
    ARRAY['map','—','地图','Navigation aid','travel','beginner'],
    ARRAY['compass','—','指南针','Direction tool','travel','intermediate'],
    ARRAY['itinerary','—','行程','Trip plan','travel','intermediate'],
    ARRAY['delay','—','延误','Late departure','travel','intermediate'],
    -- shopping
    ARRAY['price','—','价格','Cost','shopping','beginner'],
    ARRAY['discount','—','折扣','Price reduction','shopping','beginner'],
    ARRAY['sale','—','特卖','Reduced price','shopping','beginner'],
    ARRAY['receipt','—','收据','Proof of purchase','shopping','beginner'],
    ARRAY['refund','—','退款','Money back','shopping','intermediate'],
    ARRAY['exchange','—','换货','Swap item','shopping','intermediate'],
    ARRAY['cash','—','现金','Physical money','shopping','beginner'],
    ARRAY['credit card','—','信用卡','Payment card','shopping','beginner'],
    ARRAY['wallet','—','钱包','Holds money','shopping','beginner'],
    ARRAY['budget','—','预算','Spending limit','shopping','intermediate'],
    ARRAY['bargain','—','便宜货','Good deal','shopping','intermediate'],
    ARRAY['expensive','—','贵的','High cost','shopping','beginner'],
    ARRAY['affordable','—','实惠的','Reasonably priced','shopping','intermediate'],
    ARRAY['sold out','—','卖完了','No stock','shopping','intermediate'],
    ARRAY['available','—','有货','In stock','shopping','intermediate'],
    -- work
    ARRAY['job','—','工作','Employment','work','beginner'],
    ARRAY['career','—','职业','Long-term work','work','intermediate'],
    ARRAY['boss','—','老板','Manager','work','beginner'],
    ARRAY['employee','—','员工','Worker','work','intermediate'],
    ARRAY['colleague','—','同事','Co-worker','work','intermediate'],
    ARRAY['meeting','—','会议','Work gathering','work','beginner'],
    ARRAY['presentation','—','演讲','Show and tell','work','intermediate'],
    ARRAY['report','—','报告','Summary document','work','intermediate'],
    ARRAY['email','—','电子邮件','Electronic message','work','beginner'],
    ARRAY['overtime','—','加班','Extra work hours','work','intermediate'],
    ARRAY['salary','—','薪水','Regular pay','work','intermediate'],
    ARRAY['bonus','—','奖金','Extra pay','work','intermediate'],
    ARRAY['resign','—','辞职','Quit job','work','intermediate'],
    ARRAY['hire','—','雇用','Take on worker','work','intermediate'],
    ARRAY['promote','—','晋升','Advance in rank','work','intermediate'],
    ARRAY['negotiate','—','谈判','Discuss terms','work','advanced'],
    ARRAY['contract','—','合同','Legal agreement','work','intermediate'],
    ARRAY['deadline','—','截止日期','Due date','work','intermediate'],
    ARRAY['project','—','项目','Planned work','work','intermediate'],
    ARRAY['strategy','—','策略','Plan of action','work','advanced'],
    -- health
    ARRAY['doctor','—','医生','Medical professional','health','beginner'],
    ARRAY['nurse','—','护士','Medical assistant','health','beginner'],
    ARRAY['hospital','—','医院','Medical facility','health','beginner'],
    ARRAY['clinic','—','诊所','Small health centre','health','intermediate'],
    ARRAY['medicine','—','药','Treatment substance','health','beginner'],
    ARRAY['prescription','—','处方','Doctor''s order','health','intermediate'],
    ARRAY['symptom','—','症状','Sign of illness','health','intermediate'],
    ARRAY['diagnosis','—','诊断','Identifying illness','health','advanced'],
    ARRAY['treatment','—','治疗','Medical care','health','intermediate'],
    ARRAY['surgery','—','手术','Medical operation','health','advanced'],
    ARRAY['recovery','—','康复','Getting better','health','intermediate'],
    ARRAY['allergy','—','过敏','Immune reaction','health','intermediate'],
    ARRAY['vaccine','—','疫苗','Disease prevention','health','intermediate'],
    ARRAY['insurance','—','保险','Financial protection','health','intermediate'],
    ARRAY['emergency','—','紧急情况','Urgent situation','health','intermediate'],
    ARRAY['first aid','—','急救','Immediate care','health','intermediate'],
    ARRAY['chronic','—','慢性的','Long-term illness','health','advanced'],
    ARRAY['contagious','—','传染性的','Spreading disease','health','advanced'],
    ARRAY['mental health','—','心理健康','Psychological wellbeing','health','advanced'],
    ARRAY['therapy','—','治疗/疗法','Therapeutic treatment','health','advanced'],
    -- tech
    ARRAY['computer','—','电脑','Computing device','tech','beginner'],
    ARRAY['smartphone','—','智能手机','Mobile phone','tech','beginner'],
    ARRAY['internet','—','互联网','Global network','tech','beginner'],
    ARRAY['website','—','网站','Web presence','tech','beginner'],
    ARRAY['app','—','应用程序','Mobile software','tech','beginner'],
    ARRAY['software','—','软件','Computer program','tech','intermediate'],
    ARRAY['hardware','—','硬件','Physical components','tech','intermediate'],
    ARRAY['password','—','密码','Security code','tech','beginner'],
    ARRAY['username','—','用户名','Login name','tech','beginner'],
    ARRAY['download','—','下载','Get from internet','tech','beginner'],
    ARRAY['upload','—','上传','Send to internet','tech','intermediate'],
    ARRAY['update','—','更新','New version','tech','beginner'],
    ARRAY['backup','—','备份','Data copy','tech','intermediate'],
    ARRAY['virus','—','病毒','Malicious program','tech','intermediate'],
    ARRAY['firewall','—','防火墙','Network protection','tech','advanced'],
    ARRAY['cloud','—','云','Online storage','tech','intermediate'],
    ARRAY['artificial intelligence','—','人工智能','AI technology','tech','intermediate'],
    ARRAY['algorithm','—','算法','Problem-solving steps','tech','advanced'],
    ARRAY['database','—','数据库','Data storage system','tech','advanced'],
    ARRAY['cybersecurity','—','网络安全','Digital protection','tech','advanced'],
    ARRAY['programming','—','编程','Writing code','tech','intermediate'],
    ARRAY['debugging','—','调试','Fixing code errors','tech','advanced'],
    ARRAY['encryption','—','加密','Securing data','tech','advanced'],
    ARRAY['bandwidth','—','带宽','Data transfer speed','tech','advanced'],
    ARRAY['latency','—','延迟','Response delay','tech','advanced'],
    -- nature
    ARRAY['mountain','—','山','High landform','nature','beginner'],
    ARRAY['river','—','河流','Flowing water','nature','beginner'],
    ARRAY['ocean','—','海洋','Large saltwater','nature','beginner'],
    ARRAY['forest','—','森林','Dense trees','nature','beginner'],
    ARRAY['desert','—','沙漠','Dry wasteland','nature','beginner'],
    ARRAY['island','—','岛屿','Land in water','nature','beginner'],
    ARRAY['valley','—','山谷','Between mountains','nature','intermediate'],
    ARRAY['volcano','—','火山','Erupting mountain','nature','intermediate'],
    ARRAY['earthquake','—','地震','Ground shaking','nature','intermediate'],
    ARRAY['flood','—','洪水','Excessive water','nature','intermediate'],
    ARRAY['drought','—','干旱','Lack of water','nature','intermediate'],
    ARRAY['tornado','—','龙卷风','Spinning wind','nature','intermediate'],
    ARRAY['hurricane','—','飓风','Tropical storm','nature','intermediate'],
    ARRAY['ecosystem','—','生态系统','Living system','nature','advanced'],
    ARRAY['biodiversity','—','生物多样性','Variety of life','nature','advanced'],
    ARRAY['climate change','—','气候变化','Global warming','nature','advanced'],
    ARRAY['renewable energy','—','可再生能源','Clean power','nature','advanced'],
    ARRAY['carbon footprint','—','碳足迹','Emission measure','nature','advanced'],
    ARRAY['sustainability','—','可持续性','Long-term viability','nature','advanced'],
    ARRAY['conservation','—','保护','Preserving nature','nature','advanced'],
    -- emotion/personality
    ARRAY['happy','—','高兴的','Feeling joy','emotion','beginner'],
    ARRAY['sad','—','悲伤的','Feeling sorrow','emotion','beginner'],
    ARRAY['angry','—','愤怒的','Feeling rage','emotion','beginner'],
    ARRAY['scared','—','害怕的','Feeling fear','emotion','beginner'],
    ARRAY['excited','—','兴奋的','Very eager','emotion','beginner'],
    ARRAY['nervous','—','紧张的','Anxious feeling','emotion','beginner'],
    ARRAY['confident','—','自信的','Self-assured','emotion','intermediate'],
    ARRAY['embarrassed','—','尴尬的','Socially awkward','emotion','intermediate'],
    ARRAY['proud','—','自豪的','Feeling achievement','emotion','intermediate'],
    ARRAY['lonely','—','孤独的','Feeling alone','emotion','intermediate'],
    ARRAY['frustrated','—','沮丧的','Feeling blocked','emotion','intermediate'],
    ARRAY['grateful','—','感激的','Thankful feeling','emotion','intermediate'],
    ARRAY['jealous','—','嫉妒的','Envious feeling','emotion','intermediate'],
    ARRAY['anxious','—','焦虑的','Worried state','emotion','intermediate'],
    ARRAY['overwhelmed','—','不知所措的','Too much to handle','emotion','advanced'],
    ARRAY['optimistic','—','乐观的','Positive outlook','emotion','intermediate'],
    ARRAY['pessimistic','—','悲观的','Negative outlook','emotion','intermediate'],
    ARRAY['empathetic','—','有同理心的','Understanding feelings','emotion','advanced'],
    ARRAY['resilient','—','有韧性的','Bouncing back','emotion','advanced'],
    ARRAY['compassionate','—','富有同情心的','Caring for others','emotion','advanced'],
    -- family/social
    ARRAY['family','—','家人','Related people','family','beginner'],
    ARRAY['parent','—','父母','Mother or father','family','beginner'],
    ARRAY['sibling','—','兄弟姐妹','Brother or sister','family','beginner'],
    ARRAY['grandparent','—','祖父母','Grandma or grandpa','family','beginner'],
    ARRAY['relative','—','亲戚','Extended family','family','intermediate'],
    ARRAY['neighbor','—','邻居','Nearby resident','family','intermediate'],
    ARRAY['friend','—','朋友','Close companion','family','beginner'],
    ARRAY['acquaintance','—','熟人','Loose connection','family','intermediate'],
    ARRAY['community','—','社区','Local group','family','intermediate'],
    ARRAY['society','—','社会','Organised group','family','advanced'],
    -- education
    ARRAY['school','—','学校','Place of learning','study','beginner'],
    ARRAY['university','—','大学','Higher education','study','beginner'],
    ARRAY['student','—','学生','Person learning','study','beginner'],
    ARRAY['teacher','—','老师','Person teaching','study','beginner'],
    ARRAY['lesson','—','课程','Teaching session','study','beginner'],
    ARRAY['homework','—','作业','Study task','study','beginner'],
    ARRAY['exam','—','考试','Knowledge test','study','beginner'],
    ARRAY['grade','—','成绩','Score result','study','beginner'],
    ARRAY['degree','—','学位','Academic award','study','intermediate'],
    ARRAY['scholarship','—','奖学金','Study funding','study','intermediate'],
    ARRAY['curriculum','—','课程大纲','Study plan','study','advanced'],
    ARRAY['assignment','—','作业/任务','Given task','study','intermediate'],
    ARRAY['thesis','—','论文','Research paper','study','advanced'],
    ARRAY['lecture','—','讲座','Teaching talk','study','intermediate'],
    ARRAY['seminar','—','研讨会','Small group class','study','advanced'],
    ARRAY['tutor','—','辅导老师','Private teacher','study','intermediate'],
    ARRAY['library','—','图书馆','Book collection','study','beginner'],
    ARRAY['textbook','—','教材','Study book','study','beginner'],
    ARRAY['essay','—','文章','Written composition','study','intermediate'],
    ARRAY['research','—','研究','Investigation','study','intermediate'],
    -- transport
    ARRAY['car','—','汽车','Road vehicle','transport','beginner'],
    ARRAY['bus','—','公共汽车','Public transport','transport','beginner'],
    ARRAY['train','—','火车','Rail vehicle','transport','beginner'],
    ARRAY['airplane','—','飞机','Air vehicle','transport','beginner'],
    ARRAY['bicycle','—','自行车','Two-wheeled cycle','transport','beginner'],
    ARRAY['taxi','—','出租车','Hired car','transport','beginner'],
    ARRAY['subway','—','地铁','Underground train','transport','beginner'],
    ARRAY['ferry','—','渡船','Water crossing','transport','intermediate'],
    ARRAY['traffic','—','交通','Vehicle movement','transport','beginner'],
    ARRAY['highway','—','高速公路','Fast road','transport','intermediate'],
    ARRAY['intersection','—','十字路口','Road crossing','transport','intermediate'],
    ARRAY['pedestrian','—','行人','Walking person','transport','intermediate'],
    ARRAY['licence','—','驾照','Driving permit','transport','intermediate'],
    ARRAY['fuel','—','燃料','Vehicle energy','transport','intermediate'],
    ARRAY['electric vehicle','—','电动车','Battery car','transport','advanced'],
    -- advanced academic/professional
    ARRAY['hypothesis','—','假设','Unproven idea','study','advanced'],
    ARRAY['analysis','—','分析','Detailed examination','study','advanced'],
    ARRAY['synthesis','—','综合','Combining ideas','study','advanced'],
    ARRAY['evaluation','—','评估','Judging value','study','advanced'],
    ARRAY['methodology','—','方法论','Research approach','study','advanced'],
    ARRAY['perspective','—','观点','Point of view','study','advanced'],
    ARRAY['abstract','—','摘要/抽象','Summary/Non-concrete','study','advanced'],
    ARRAY['implication','—','含义/影响','Meaning/Effect','study','advanced'],
    ARRAY['paradigm','—','范式','Model or example','study','advanced'],
    ARRAY['consensus','—','共识','General agreement','study','advanced'],
    ARRAY['ambiguous','—','模糊的','Unclear meaning','daily','advanced'],
    ARRAY['explicit','—','明确的','Clearly stated','daily','advanced'],
    ARRAY['implicit','—','隐含的','Not directly stated','daily','advanced'],
    ARRAY['coherent','—','连贯的','Logically consistent','daily','advanced'],
    ARRAY['concise','—','简洁的','Briefly expressed','daily','advanced'],
    ARRAY['elaborate','—','详细说明','Explain in detail','daily','advanced'],
    ARRAY['justify','—','证明正当','Give reasons','daily','advanced'],
    ARRAY['contradict','—','反驳','Oppose statement','daily','advanced'],
    ARRAY['emphasize','—','强调','Give importance','daily','advanced'],
    ARRAY['paraphrase','—','改述','Restate in own words','daily','advanced'],
    -- home
    ARRAY['house','—','房子','Dwelling','home','beginner'],
    ARRAY['apartment','—','公寓','Flat','home','beginner'],
    ARRAY['kitchen','—','厨房','Cooking room','home','beginner'],
    ARRAY['bedroom','—','卧室','Sleeping room','home','beginner'],
    ARRAY['bathroom','—','浴室','Washing room','home','beginner'],
    ARRAY['living room','—','客厅','Relaxing room','home','beginner'],
    ARRAY['furniture','—','家具','Room items','home','intermediate'],
    ARRAY['appliance','—','家用电器','Household machine','home','intermediate'],
    ARRAY['rent','—','租金','Payment for home','home','intermediate'],
    ARRAY['mortgage','—','抵押贷款','Home loan','home','advanced'],
    -- extra verbs/expressions
    ARRAY['achieve','—','实现','Reach a goal','daily','intermediate'],
    ARRAY['accomplish','—','完成','Finish successfully','daily','intermediate'],
    ARRAY['improve','—','改善','Make better','daily','intermediate'],
    ARRAY['develop','—','发展','Grow/Create','daily','intermediate'],
    ARRAY['maintain','—','维护','Keep going','daily','intermediate'],
    ARRAY['reduce','—','减少','Make less','daily','intermediate'],
    ARRAY['increase','—','增加','Make more','daily','intermediate'],
    ARRAY['identify','—','识别','Find/Name','daily','intermediate'],
    ARRAY['consider','—','考虑','Think about','daily','intermediate'],
    ARRAY['determine','—','确定','Decide/Find out','daily','intermediate'],
    ARRAY['ensure','—','确保','Make certain','daily','intermediate'],
    ARRAY['require','—','要求','Need/Demand','daily','intermediate'],
    ARRAY['provide','—','提供','Give/Supply','daily','intermediate'],
    ARRAY['establish','—','建立','Set up/Found','daily','advanced'],
    ARRAY['implement','—','实施','Put into action','daily','advanced'],
    ARRAY['allocate','—','分配','Assign resources','daily','advanced'],
    ARRAY['facilitate','—','促进','Make easier','daily','advanced'],
    ARRAY['collaborate','—','合作','Work together','daily','advanced'],
    ARRAY['communicate','—','交流','Share information','daily','intermediate'],
    ARRAY['demonstrate','—','演示','Show/Prove','daily','intermediate'],
    ARRAY['acknowledge','—','承认','Recognise/Accept','daily','advanced'],
    ARRAY['anticipate','—','预期','Expect beforehand','daily','advanced'],
    ARRAY['contribute','—','贡献','Give to a cause','daily','intermediate'],
    ARRAY['coordinate','—','协调','Organise together','daily','advanced'],
    ARRAY['distinguish','—','区分','Tell apart','daily','advanced'],
    ARRAY['enhance','—','增强','Improve quality','daily','advanced'],
    ARRAY['generate','—','产生','Create/Produce','daily','advanced'],
    ARRAY['integrate','—','整合','Combine into whole','daily','advanced'],
    ARRAY['interpret','—','解释','Explain meaning','daily','advanced'],
    ARRAY['monitor','—','监控','Watch over','daily','advanced'],
    ARRAY['negotiate','—','谈判','Discuss terms','daily','advanced'],
    ARRAY['perceive','—','感知','Notice/Understand','daily','advanced'],
    ARRAY['prioritise','—','优先考虑','Rank by importance','daily','advanced'],
    ARRAY['resolve','—','解决','Fix a problem','daily','advanced'],
    ARRAY['respond','—','回应','React to','daily','intermediate'],
    ARRAY['sustain','—','维持','Keep going long-term','daily','advanced'],
    ARRAY['utilise','—','利用','Make use of','daily','advanced'],
    ARRAY['validate','—','验证','Confirm correct','daily','advanced'],
    ARRAY['verify','—','核实','Check accuracy','daily','advanced']
  ];
  i integer;
BEGIN
  FOR i IN 1..array_length(en_words, 1) LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index)
    VALUES (
      'en',
      en_words[i][1],
      en_words[i][2],
      en_words[i][3],
      en_words[i][4],
      en_words[i][5],
      en_words[i][6],
      i
    )
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;
