/*
  # Seed Italian, Portuguese, Arabic, Chinese (zh) Vocabulary

  Adds ~200+ entries per language for Italian, Portuguese, Arabic, and Chinese advanced,
  targeting the vocabulary_items table using correct schema columns.
  Uses ON CONFLICT DO NOTHING for safe idempotent inserts.

  Columns used: language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index
*/

DO $$
DECLARE
  -- Each entry: word, reading, meaning_zh, meaning_en, tag
  it_words text[][] := ARRAY[
    ARRAY['ciao','tʃao','你好','hello / bye','greeting'],
    ARRAY['grazie','ɡrattsje','谢谢','thank you','courtesy'],
    ARRAY['prego','preɡo','不客气','you''re welcome','courtesy'],
    ARRAY['per favore','per faˈvore','请','please','courtesy'],
    ARRAY['scusi','ˈskuzi','打扰了','excuse me','courtesy'],
    ARRAY['sì','si','是','yes','basic'],
    ARRAY['no','no','不','no','basic'],
    ARRAY['buongiorno','bwonˈdʒorno','早上好','good morning','greeting'],
    ARRAY['buonasera','bwɔnaˈsera','晚上好','good evening','greeting'],
    ARRAY['arrivederci','arrivedˈertʃi','再见','goodbye','greeting'],
    ARRAY['come stai','kome ˈstai','你好吗','how are you','greeting'],
    ARRAY['bene','ˈbene','好','well / good','response'],
    ARRAY['male','ˈmale','不好','bad / poorly','response'],
    ARRAY['così così','koˈzi koˈzi','还好','so-so','response'],
    ARRAY['mi chiamo','mi ˈkjamo','我叫','my name is','introduction'],
    ARRAY['piacere','pjaˈtʃere','幸会','nice to meet you','introduction'],
    ARRAY['dove','ˈdove','哪里','where','question_word'],
    ARRAY['quando','ˈkwando','什么时候','when','question_word'],
    ARRAY['quanto','ˈkwanto','多少','how much','question_word'],
    ARRAY['perché','perˈke','为什么','why / because','question_word'],
    ARRAY['come','ˈkome','怎么','how','question_word'],
    ARRAY['chi','ki','谁','who','question_word'],
    ARRAY['che cosa','ke ˈkɔza','什么','what','question_word'],
    ARRAY['acqua','ˈakkwa','水','water','food'],
    ARRAY['vino','ˈvino','葡萄酒','wine','food'],
    ARRAY['caffè','kafˈfɛ','咖啡','coffee','food'],
    ARRAY['pane','ˈpane','面包','bread','food'],
    ARRAY['pasta','ˈpasta','意大利面','pasta','food'],
    ARRAY['pizza','ˈpittsa','比萨','pizza','food'],
    ARRAY['carne','ˈkarne','肉','meat','food'],
    ARRAY['pesce','ˈpeʃʃe','鱼','fish','food'],
    ARRAY['verdura','verˈdura','蔬菜','vegetables','food'],
    ARRAY['frutta','ˈfrutta','水果','fruit','food'],
    ARRAY['latte','ˈlatte','牛奶','milk','food'],
    ARRAY['formaggio','forˈmaddʒo','奶酪','cheese','food'],
    ARRAY['uovo','ˈwɔvo','鸡蛋','egg','food'],
    ARRAY['pollo','ˈpollo','鸡肉','chicken','food'],
    ARRAY['riso','ˈrizo','米饭','rice','food'],
    ARRAY['zucchero','ˈdzukkero','糖','sugar','food'],
    ARRAY['sale','ˈsale','盐','salt','food'],
    ARRAY['uno','ˈuno','一','one','numbers'],
    ARRAY['due','ˈdue','二','two','numbers'],
    ARRAY['tre','tre','三','three','numbers'],
    ARRAY['quattro','ˈkwattro','四','four','numbers'],
    ARRAY['cinque','ˈtʃinkwe','五','five','numbers'],
    ARRAY['sei','sei','六','six','numbers'],
    ARRAY['sette','ˈsette','七','seven','numbers'],
    ARRAY['otto','ˈɔtto','八','eight','numbers'],
    ARRAY['nove','ˈnɔve','九','nine','numbers'],
    ARRAY['dieci','ˈdjɛtʃi','十','ten','numbers'],
    ARRAY['venti','ˈventi','二十','twenty','numbers'],
    ARRAY['cento','ˈtʃento','百','hundred','numbers'],
    ARRAY['mille','ˈmille','千','thousand','numbers'],
    ARRAY['lunedì','luneˈdi','星期一','Monday','days'],
    ARRAY['martedì','marteˈdi','星期二','Tuesday','days'],
    ARRAY['mercoledì','merkoleˈdi','星期三','Wednesday','days'],
    ARRAY['giovedì','dʒoveˈdi','星期四','Thursday','days'],
    ARRAY['venerdì','venerˈdi','星期五','Friday','days'],
    ARRAY['sabato','ˈsabato','星期六','Saturday','days'],
    ARRAY['domenica','doˈmenika','星期日','Sunday','days'],
    ARRAY['oggi','ˈɔddʒi','今天','today','time'],
    ARRAY['ieri','ˈjɛri','昨天','yesterday','time'],
    ARRAY['domani','doˈmani','明天','tomorrow','time'],
    ARRAY['mattina','matˈtina','早上','morning','time'],
    ARRAY['pomeriggio','pomeˈriddʒo','下午','afternoon','time'],
    ARRAY['sera','ˈsera','傍晚','evening','time'],
    ARRAY['notte','ˈnɔtte','夜晚','night','time'],
    ARRAY['adesso','aˈdesso','现在','now','time'],
    ARRAY['dopo','ˈdopo','之后','after / later','time'],
    ARRAY['prima','ˈprima','之前','before / first','time'],
    ARRAY['sempre','ˈsempre','总是','always','time'],
    ARRAY['mai','mai','从不','never','time'],
    ARRAY['spesso','ˈspesso','经常','often','time'],
    ARRAY['casa','ˈkaza','家','house / home','places'],
    ARRAY['ufficio','ufˈfitʃo','办公室','office','places'],
    ARRAY['scuola','ˈskwɔla','学校','school','places'],
    ARRAY['ospedale','ospeˈdale','医院','hospital','places'],
    ARRAY['ristorante','ristoˈrante','餐厅','restaurant','places'],
    ARRAY['negozio','neˈɡɔtsjo','商店','shop / store','places'],
    ARRAY['supermercato','supermerkato','超市','supermarket','places'],
    ARRAY['banca','ˈbaŋka','银行','bank','places'],
    ARRAY['farmacia','farmaˈtʃia','药店','pharmacy','places'],
    ARRAY['stazione','statˈtsjone','车站','station','places'],
    ARRAY['aeroporto','aeroporto','机场','airport','places'],
    ARRAY['hotel','oˈtɛl','酒店','hotel','places'],
    ARRAY['spiaggia','ˈspjaddʒa','海滩','beach','places'],
    ARRAY['montagna','monˈtaɲɲa','山','mountain','nature'],
    ARRAY['mare','ˈmare','海','sea','nature'],
    ARRAY['lago','ˈlaɡo','湖','lake','nature'],
    ARRAY['fiume','ˈfjume','河流','river','nature'],
    ARRAY['foresta','foˈrɛsta','森林','forest','nature'],
    ARRAY['cielo','ˈtʃɛlo','天空','sky','nature'],
    ARRAY['sole','ˈsole','太阳','sun','nature'],
    ARRAY['luna','ˈluna','月亮','moon','nature'],
    ARRAY['stella','ˈstɛlla','星星','star','nature'],
    ARRAY['pioggia','ˈpjɔddʒa','雨','rain','nature'],
    ARRAY['neve','ˈneve','雪','snow','nature'],
    ARRAY['vento','ˈvento','风','wind','nature'],
    ARRAY['uomo','ˈwɔmo','男人','man','people'],
    ARRAY['donna','ˈdɔnna','女人','woman','people'],
    ARRAY['bambino','bamˈbino','男孩','child (boy)','people'],
    ARRAY['amico','aˈmiko','朋友（男）','friend (m)','people'],
    ARRAY['amica','aˈmika','朋友（女）','friend (f)','people'],
    ARRAY['padre','ˈpadre','父亲','father','family'],
    ARRAY['madre','ˈmadre','母亲','mother','family'],
    ARRAY['fratello','fraˈtɛllo','兄弟','brother','family'],
    ARRAY['sorella','soˈrɛlla','姐妹','sister','family'],
    ARRAY['figlio','ˈfiʎʎo','儿子','son','family'],
    ARRAY['figlia','ˈfiʎʎa','女儿','daughter','family'],
    ARRAY['nonno','ˈnɔnno','祖父','grandfather','family'],
    ARRAY['nonna','ˈnɔnna','祖母','grandmother','family'],
    ARRAY['marito','maˈrito','丈夫','husband','family'],
    ARRAY['moglie','ˈmɔʎʎe','妻子','wife','family'],
    ARRAY['grande','ˈɡrande','大','big / great','adjectives'],
    ARRAY['piccolo','ˈpikkolo','小','small','adjectives'],
    ARRAY['bello','ˈbɛllo','漂亮','beautiful','adjectives'],
    ARRAY['brutto','ˈbrutto','丑','ugly','adjectives'],
    ARRAY['buono','ˈbwɔno','好','good','adjectives'],
    ARRAY['cattivo','katˈtivo','坏','bad','adjectives'],
    ARRAY['nuovo','ˈnwɔvo','新','new','adjectives'],
    ARRAY['vecchio','ˈvekkjo','旧','old','adjectives'],
    ARRAY['caldo','ˈkaldo','热','hot','adjectives'],
    ARRAY['freddo','ˈfrɛddo','冷','cold','adjectives'],
    ARRAY['facile','ˈfatʃile','容易','easy','adjectives'],
    ARRAY['difficile','difˈfitʃile','难','difficult','adjectives'],
    ARRAY['veloce','veˈlotʃe','快','fast','adjectives'],
    ARRAY['lento','ˈlento','慢','slow','adjectives'],
    ARRAY['alto','ˈalto','高','tall / high','adjectives'],
    ARRAY['basso','ˈbasso','矮','short / low','adjectives'],
    ARRAY['essere','ˈɛssere','是','to be','verbs'],
    ARRAY['avere','aˈvere','有','to have','verbs'],
    ARRAY['fare','ˈfare','做','to do / make','verbs'],
    ARRAY['andare','anˈdare','去','to go','verbs'],
    ARRAY['venire','veˈnire','来','to come','verbs'],
    ARRAY['parlare','parˈlare','说话','to speak','verbs'],
    ARRAY['mangiare','manˈdʒare','吃','to eat','verbs'],
    ARRAY['bere','ˈbere','喝','to drink','verbs'],
    ARRAY['dormire','dorˈmire','睡觉','to sleep','verbs'],
    ARRAY['lavorare','lavoˈrare','工作','to work','verbs'],
    ARRAY['studiare','stuˈdjare','学习','to study','verbs'],
    ARRAY['capire','kaˈpire','明白','to understand','verbs'],
    ARRAY['sapere','saˈpere','知道','to know','verbs'],
    ARRAY['potere','poˈtere','能','to be able','verbs'],
    ARRAY['volere','voˈlere','想要','to want','verbs'],
    ARRAY['dovere','doˈvere','必须','to have to / must','verbs'],
    ARRAY['vedere','veˈdere','看','to see','verbs'],
    ARRAY['sentire','senˈtire','听/感觉','to hear / feel','verbs'],
    ARRAY['leggere','ˈlɛddʒere','读','to read','verbs'],
    ARRAY['scrivere','ˈskrivere','写','to write','verbs'],
    ARRAY['comprare','komˈprare','买','to buy','verbs'],
    ARRAY['pagare','paˈɡare','付钱','to pay','verbs'],
    ARRAY['aspettare','aspetˈtare','等待','to wait','verbs'],
    ARRAY['aiutare','ajuˈtare','帮助','to help','verbs'],
    ARRAY['trovare','troˈvare','找到','to find','verbs'],
    ARRAY['aprire','aˈprire','打开','to open','verbs'],
    ARRAY['chiudere','ˈkjudere','关闭','to close','verbs'],
    ARRAY['chiamare','kjaˈmare','打电话','to call','verbs'],
    ARRAY['prenotare','prenoˈtare','预订','to reserve','travel'],
    ARRAY['treno','ˈtreno','火车','train','travel'],
    ARRAY['autobus','ˈautobus','公共汽车','bus','travel'],
    ARRAY['taxi','ˈtaksi','出租车','taxi','travel'],
    ARRAY['macchina','ˈmakkina','汽车','car','travel'],
    ARRAY['bicicletta','bitʃiˈkletta','自行车','bicycle','travel'],
    ARRAY['biglietto','biʎˈʎetto','票','ticket','travel'],
    ARRAY['passaporto','passaˈpɔrto','护照','passport','travel'],
    ARRAY['valigia','vaˈlidʒa','行李箱','suitcase','travel'],
    ARRAY['mappa','ˈmappa','地图','map','travel'],
    ARRAY['strada','ˈstrada','街道','street / road','city'],
    ARRAY['piazza','ˈpjattsa','广场','square / plaza','city'],
    ARRAY['ponte','ˈponte','桥','bridge','city'],
    ARRAY['chiesa','ˈkjɛza','教堂','church','city'],
    ARRAY['museo','muˈzɛo','博物馆','museum','city'],
    ARRAY['parco','ˈparko','公园','park','city'],
    ARRAY['soldi','ˈsoldi','钱','money','lifestyle'],
    ARRAY['prezzo','ˈprɛttso','价格','price','shopping'],
    ARRAY['sconto','ˈskonto','折扣','discount','shopping'],
    ARRAY['taglia','ˈtaʎʎa','尺码','size','shopping'],
    ARRAY['colore','koˈlore','颜色','color','shopping'],
    ARRAY['regalo','reˈɡalo','礼物','gift','shopping'],
    ARRAY['cassa','ˈkassa','收银台','cashier','shopping'],
    ARRAY['scarpe','ˈskarpe','鞋子','shoes','clothing'],
    ARRAY['cappello','kapˈpɛllo','帽子','hat','clothing'],
    ARRAY['giacca','ˈdʒakka','外套','jacket','clothing'],
    ARRAY['pantaloni','pantalˈoni','裤子','trousers','clothing'],
    ARRAY['camicia','kaˈmitʃa','衬衫','shirt','clothing'],
    ARRAY['medico','ˈmɛdiko','医生','doctor','health'],
    ARRAY['dolore','doˈlore','疼痛','pain','health'],
    ARRAY['febbre','ˈfɛbbre','发烧','fever','health'],
    ARRAY['medicina','mediˈtʃina','药','medicine','health'],
    ARRAY['allergia','allerˈdʒia','过敏','allergy','health'],
    ARRAY['emergenza','emerˈdʒɛntsa','紧急情况','emergency','health'],
    ARRAY['telefono','teˈlɛfono','电话','phone','technology'],
    ARRAY['computer','komˈpjuter','电脑','computer','technology'],
    ARRAY['internet','ˈinternet','网络','internet','technology'],
    ARRAY['messaggio','mesˈsaddʒo','消息','message','technology'],
    ARRAY['password','ˈpasword','密码','password','technology'],
    ARRAY['rosso','ˈrɔsso','红色','red','colors'],
    ARRAY['blu','blu','蓝色','blue','colors'],
    ARRAY['verde','ˈverde','绿色','green','colors'],
    ARRAY['giallo','ˈdʒallo','黄色','yellow','colors'],
    ARRAY['bianco','ˈbjaŋko','白色','white','colors'],
    ARRAY['nero','ˈnero','黑色','black','colors'],
    ARRAY['grigio','ˈɡridʒo','灰色','gray','colors'],
    ARRAY['arancione','aranˈtʃone','橙色','orange','colors'],
    ARRAY['rosa','ˈrɔza','粉色','pink','colors'],
    ARRAY['marrone','marˈrone','棕色','brown','colors'],
    ARRAY['io','io','我','I / me','pronouns'],
    ARRAY['tu','tu','你','you (sing)','pronouns'],
    ARRAY['lui','lui','他','he','pronouns'],
    ARRAY['lei','lei','她/您','she / you (formal)','pronouns'],
    ARRAY['noi','noi','我们','we','pronouns'],
    ARRAY['voi','voi','你们','you (plural)','pronouns'],
    ARRAY['loro','ˈloro','他们','they','pronouns'],
    ARRAY['questo','ˈkwesto','这个','this','demonstratives'],
    ARRAY['quello','ˈkwello','那个','that','demonstratives'],
    ARRAY['qui','kwi','这里','here','location'],
    ARRAY['sopra','ˈsopra','上面','above','location'],
    ARRAY['sotto','ˈsotto','下面','below','location'],
    ARRAY['dentro','ˈdentro','里面','inside','location'],
    ARRAY['fuori','ˈfwɔri','外面','outside','location'],
    ARRAY['vicino','viˈtʃino','附近','near','location'],
    ARRAY['lontano','lonˈtano','远','far','location'],
    ARRAY['destra','ˈdɛstra','右边','right','direction'],
    ARRAY['sinistra','siˈnistra','左边','left','direction'],
    ARRAY['dritto','ˈdritto','直走','straight','direction'],
    ARRAY['mese','ˈmese','月','month','calendar'],
    ARRAY['anno','ˈanno','年','year','calendar'],
    ARRAY['settimana','settiˈmana','周','week','calendar'],
    ARRAY['gennaio','dʒenˈnajo','一月','January','months'],
    ARRAY['febbraio','febˈbrajo','二月','February','months'],
    ARRAY['marzo','ˈmartso','三月','March','months'],
    ARRAY['aprile','aˈprile','四月','April','months'],
    ARRAY['maggio','ˈmaddʒo','五月','May','months'],
    ARRAY['giugno','ˈdʒuɲɲo','六月','June','months'],
    ARRAY['luglio','ˈluʎʎo','七月','July','months'],
    ARRAY['agosto','aˈɡosto','八月','August','months'],
    ARRAY['settembre','setˈtembre','九月','September','months'],
    ARRAY['ottobre','otˈtobre','十月','October','months'],
    ARRAY['novembre','noˈvembre','十一月','November','months'],
    ARRAY['dicembre','diˈtʃembre','十二月','December','months']
  ];

  pt_words text[][] := ARRAY[
    ARRAY['olá','ɔˈla','你好','hello','greeting'],
    ARRAY['oi','oi','嗨','hi (Brazil)','greeting'],
    ARRAY['obrigado','obriˈɡadu','谢谢（男）','thank you (m)','courtesy'],
    ARRAY['obrigada','obriˈɡada','谢谢（女）','thank you (f)','courtesy'],
    ARRAY['por favor','pur faˈvor','请','please','courtesy'],
    ARRAY['de nada','di ˈnada','不客气','you''re welcome','courtesy'],
    ARRAY['desculpe','diʃˈkulpi','对不起','excuse me / sorry','courtesy'],
    ARRAY['sim','sĩ','是','yes','basic'],
    ARRAY['não','nɐ̃w','不','no','basic'],
    ARRAY['bom dia','bõ ˈdiɐ','早上好','good morning','greeting'],
    ARRAY['boa tarde','ˈboɐ ˈtardi','下午好','good afternoon','greeting'],
    ARRAY['boa noite','ˈboɐ ˈnoiti','晚上好','good night','greeting'],
    ARRAY['tchau','ˈtʃaw','拜拜','bye (Brazil)','greeting'],
    ARRAY['adeus','aˈdewʃ','再见','goodbye','greeting'],
    ARRAY['como vai','ˈkomu ˈvaj','你好吗','how are you','greeting'],
    ARRAY['tudo bem','ˈtudu bẽj','一切都好','all good','response'],
    ARRAY['mais ou menos','ˈmajʃ u ˈmenuʃ','还好','more or less','response'],
    ARRAY['me chamo','mi ˈʃɐmu','我叫','my name is','introduction'],
    ARRAY['prazer','praˈzer','幸会','nice to meet you','introduction'],
    ARRAY['onde','ˈõdi','哪里','where','question_word'],
    ARRAY['quando','ˈkwɐ̃du','什么时候','when','question_word'],
    ARRAY['quanto','ˈkwɐ̃tu','多少','how much','question_word'],
    ARRAY['por que','pur ˈki','为什么','why','question_word'],
    ARRAY['como','ˈkomu','怎么','how','question_word'],
    ARRAY['quem','kẽj','谁','who','question_word'],
    ARRAY['o que','u ˈki','什么','what','question_word'],
    ARRAY['água','ˈaɡwɐ','水','water','food'],
    ARRAY['café','kaˈfɛ','咖啡','coffee','food'],
    ARRAY['leite','ˈlejtʃi','牛奶','milk','food'],
    ARRAY['suco','ˈsuku','果汁','juice','food'],
    ARRAY['cerveja','serˈvejɐ','啤酒','beer','food'],
    ARRAY['vinho','ˈviɲu','葡萄酒','wine','food'],
    ARRAY['pão','pɐ̃w','面包','bread','food'],
    ARRAY['arroz','aˈʁoʃ','米饭','rice','food'],
    ARRAY['feijão','fejˈʒɐ̃w','豆子','beans','food'],
    ARRAY['frango','ˈfrɐ̃ɡu','鸡肉','chicken','food'],
    ARRAY['carne','ˈkarni','肉','meat','food'],
    ARRAY['peixe','ˈpejʃi','鱼','fish','food'],
    ARRAY['fruta','ˈfrutɐ','水果','fruit','food'],
    ARRAY['legume','liˈɡumi','蔬菜','vegetable','food'],
    ARRAY['queijo','ˈkejʒu','奶酪','cheese','food'],
    ARRAY['ovo','ˈovu','鸡蛋','egg','food'],
    ARRAY['açúcar','aˈsukar','糖','sugar','food'],
    ARRAY['sal','saw','盐','salt','food'],
    ARRAY['um','ũ','一','one','numbers'],
    ARRAY['dois','dojs','二','two','numbers'],
    ARRAY['três','tɾeʃ','三','three','numbers'],
    ARRAY['quatro','ˈkwatɾu','四','four','numbers'],
    ARRAY['cinco','ˈsĩku','五','five','numbers'],
    ARRAY['seis','sejʃ','六','six','numbers'],
    ARRAY['sete','ˈsɛtʃi','七','seven','numbers'],
    ARRAY['oito','ˈojtu','八','eight','numbers'],
    ARRAY['nove','ˈnɔvi','九','nine','numbers'],
    ARRAY['dez','deʃ','十','ten','numbers'],
    ARRAY['vinte','ˈvĩtʃi','二十','twenty','numbers'],
    ARRAY['cem','sẽj','百','hundred','numbers'],
    ARRAY['mil','miw','千','thousand','numbers'],
    ARRAY['segunda-feira','seˈɡũdɐ ˈfejɾɐ','星期一','Monday','days'],
    ARRAY['terça-feira','ˈteʁsɐ ˈfejɾɐ','星期二','Tuesday','days'],
    ARRAY['quarta-feira','ˈkwaʁtɐ ˈfejɾɐ','星期三','Wednesday','days'],
    ARRAY['quinta-feira','ˈkĩtɐ ˈfejɾɐ','星期四','Thursday','days'],
    ARRAY['sexta-feira','ˈseʃtɐ ˈfejɾɐ','星期五','Friday','days'],
    ARRAY['sábado','ˈsabadu','星期六','Saturday','days'],
    ARRAY['domingo','duˈmĩɡu','星期日','Sunday','days'],
    ARRAY['hoje','ˈɔʒi','今天','today','time'],
    ARRAY['ontem','ˈõtẽj','昨天','yesterday','time'],
    ARRAY['amanhã','amɐˈɲɐ̃','明天','tomorrow','time'],
    ARRAY['manhã','mɐˈɲɐ̃','早上','morning','time'],
    ARRAY['tarde','ˈtardi','下午','afternoon','time'],
    ARRAY['noite','ˈnojtʃi','夜晚','night','time'],
    ARRAY['agora','aˈɡɔrɐ','现在','now','time'],
    ARRAY['depois','diˈpojʃ','之后','after / later','time'],
    ARRAY['antes','ˈɐ̃tʃiʃ','之前','before','time'],
    ARRAY['sempre','ˈsẽpɾi','总是','always','time'],
    ARRAY['nunca','ˈnũkɐ','从不','never','time'],
    ARRAY['casa','ˈkazɐ','家','house / home','places'],
    ARRAY['escritório','esˈkɾiˌtɔɾju','办公室','office','places'],
    ARRAY['escola','esˈkɔlɐ','学校','school','places'],
    ARRAY['hospital','ospiˈtaw','医院','hospital','places'],
    ARRAY['restaurante','ʁestawˈrɐ̃tʃi','餐厅','restaurant','places'],
    ARRAY['loja','ˈlɔʒɐ','商店','store / shop','places'],
    ARRAY['supermercado','supermɛrˈkadu','超市','supermarket','places'],
    ARRAY['banco','ˈbɐ̃ku','银行','bank','places'],
    ARRAY['farmácia','farˈmasʲɐ','药店','pharmacy','places'],
    ARRAY['aeroporto','ˌaɛɾoˈpɔʁtu','机场','airport','places'],
    ARRAY['hotel','oˈtew','酒店','hotel','places'],
    ARRAY['praia','ˈpɾajɐ','海滩','beach','places'],
    ARRAY['montanha','mõˈtɐɲɐ','山','mountain','nature'],
    ARRAY['rio','ˈʁiu','河流','river','nature'],
    ARRAY['mar','mar','海','sea','nature'],
    ARRAY['floresta','floˈɾɛstɐ','森林','forest','nature'],
    ARRAY['céu','sɛw','天空','sky','nature'],
    ARRAY['sol','sow','太阳','sun','nature'],
    ARRAY['lua','ˈluɐ','月亮','moon','nature'],
    ARRAY['estrela','eʃˈtɾelɐ','星星','star','nature'],
    ARRAY['chuva','ˈʃuvɐ','雨','rain','nature'],
    ARRAY['vento','ˈvẽtu','风','wind','nature'],
    ARRAY['homem','ˈomẽj','男人','man','people'],
    ARRAY['mulher','muˈʎɛr','女人','woman','people'],
    ARRAY['criança','kɾiˈɐ̃sɐ','孩子','child','people'],
    ARRAY['amigo','aˈmiɡu','朋友（男）','friend (m)','people'],
    ARRAY['amiga','aˈmiɡɐ','朋友（女）','friend (f)','people'],
    ARRAY['pai','paj','父亲','father','family'],
    ARRAY['mãe','mɐ̃j','母亲','mother','family'],
    ARRAY['irmão','iʁˈmɐ̃w','兄弟','brother','family'],
    ARRAY['irmã','iʁˈmɐ̃','姐妹','sister','family'],
    ARRAY['filho','ˈfiʎu','儿子','son','family'],
    ARRAY['filha','ˈfiʎɐ','女儿','daughter','family'],
    ARRAY['avô','aˈvo','祖父','grandfather','family'],
    ARRAY['avó','aˈvɔ','祖母','grandmother','family'],
    ARRAY['marido','maˈɾidu','丈夫','husband','family'],
    ARRAY['esposa','eʃˈpozɐ','妻子','wife','family'],
    ARRAY['grande','ˈɡɾɐ̃di','大','big','adjectives'],
    ARRAY['pequeno','piˈkenu','小','small','adjectives'],
    ARRAY['bonito','buˈnitu','漂亮','beautiful','adjectives'],
    ARRAY['feio','ˈfeju','丑','ugly','adjectives'],
    ARRAY['bom','bõ','好','good','adjectives'],
    ARRAY['ruim','ˈʁuĩ','坏','bad','adjectives'],
    ARRAY['novo','ˈnovu','新','new','adjectives'],
    ARRAY['velho','ˈveʎu','旧','old','adjectives'],
    ARRAY['quente','ˈkẽtʃi','热','hot','adjectives'],
    ARRAY['frio','ˈfɾiu','冷','cold','adjectives'],
    ARRAY['fácil','ˈfasiw','容易','easy','adjectives'],
    ARRAY['difícil','diˈfisiw','难','difficult','adjectives'],
    ARRAY['rápido','ˈʁapidu','快','fast','adjectives'],
    ARRAY['lento','ˈlẽtu','慢','slow','adjectives'],
    ARRAY['alto','ˈawtu','高','tall','adjectives'],
    ARRAY['baixo','ˈbajʃu','矮','short / low','adjectives'],
    ARRAY['ser','ser','是（固定）','to be (permanent)','verbs'],
    ARRAY['estar','eʃˈtar','是（临时）','to be (temporary)','verbs'],
    ARRAY['ter','ter','有','to have','verbs'],
    ARRAY['fazer','faˈzer','做','to do / make','verbs'],
    ARRAY['ir','ir','去','to go','verbs'],
    ARRAY['vir','vir','来','to come','verbs'],
    ARRAY['falar','faˈlar','说话','to speak','verbs'],
    ARRAY['comer','koˈmer','吃','to eat','verbs'],
    ARRAY['beber','beˈber','喝','to drink','verbs'],
    ARRAY['dormir','dorˈmir','睡觉','to sleep','verbs'],
    ARRAY['trabalhar','tɾabaˈʎar','工作','to work','verbs'],
    ARRAY['estudar','eʃtuˈdar','学习','to study','verbs'],
    ARRAY['entender','ẽtẽˈder','明白','to understand','verbs'],
    ARRAY['saber','saˈber','知道','to know','verbs'],
    ARRAY['poder','puˈder','能','to be able','verbs'],
    ARRAY['querer','kiˈɾer','想要','to want','verbs'],
    ARRAY['ver','ver','看','to see','verbs'],
    ARRAY['ouvir','oˈvir','听','to hear','verbs'],
    ARRAY['ler','ler','读','to read','verbs'],
    ARRAY['escrever','eʃkɾeˈver','写','to write','verbs'],
    ARRAY['comprar','kõˈpɾar','买','to buy','verbs'],
    ARRAY['pagar','paˈɡar','付钱','to pay','verbs'],
    ARRAY['esperar','eʃpeˈɾar','等待','to wait','verbs'],
    ARRAY['ajudar','aʒuˈdar','帮助','to help','verbs'],
    ARRAY['encontrar','ẽkõˈtɾar','找到/遇见','to find / meet','verbs'],
    ARRAY['abrir','aˈbɾir','打开','to open','verbs'],
    ARRAY['fechar','feˈʃar','关闭','to close','verbs'],
    ARRAY['ligar','liˈɡar','打电话','to call','verbs'],
    ARRAY['trem','tɾẽj','火车','train','travel'],
    ARRAY['ônibus','ˈonibuʃ','公共汽车','bus','travel'],
    ARRAY['táxi','ˈtaksi','出租车','taxi','travel'],
    ARRAY['carro','ˈkaʁu','汽车','car','travel'],
    ARRAY['bicicleta','bisiˈklɛtɐ','自行车','bicycle','travel'],
    ARRAY['passagem','paˈsaʒẽj','票','ticket','travel'],
    ARRAY['passaporte','pasaˈpɔʁtʃi','护照','passport','travel'],
    ARRAY['mala','ˈmalɐ','行李','suitcase','travel'],
    ARRAY['mapa','ˈmapɐ','地图','map','travel'],
    ARRAY['rua','ˈʁuɐ','街道','street','city'],
    ARRAY['praça','ˈpɾasɐ','广场','square / plaza','city'],
    ARRAY['ponte','ˈpõtʃi','桥','bridge','city'],
    ARRAY['parque','ˈpaʁki','公园','park','city'],
    ARRAY['museu','muˈzew','博物馆','museum','city'],
    ARRAY['dinheiro','dʒiˈɲejɾu','钱','money','lifestyle'],
    ARRAY['preço','ˈpɾesu','价格','price','shopping'],
    ARRAY['desconto','diʃˈkõtu','折扣','discount','shopping'],
    ARRAY['tamanho','taˈmɐɲu','尺码','size','shopping'],
    ARRAY['cor','kor','颜色','color','shopping'],
    ARRAY['presente','pɾiˈzẽtʃi','礼物','gift','shopping'],
    ARRAY['sapato','saˈpatu','鞋子','shoe','clothing'],
    ARRAY['chapéu','ʃaˈpɛw','帽子','hat','clothing'],
    ARRAY['jaqueta','ʒaˈketɐ','外套','jacket','clothing'],
    ARRAY['calça','ˈkawsɐ','裤子','trousers','clothing'],
    ARRAY['camisa','kaˈmizɐ','衬衫','shirt','clothing'],
    ARRAY['médico','ˈmɛdiku','医生','doctor','health'],
    ARRAY['dor','dor','疼痛','pain','health'],
    ARRAY['febre','ˈfɛbɾi','发烧','fever','health'],
    ARRAY['remédio','ʁiˈmɛdʒu','药','medicine','health'],
    ARRAY['alergia','aleʁˈʒiɐ','过敏','allergy','health'],
    ARRAY['emergência','emeʁˈʒẽsjɐ','紧急情况','emergency','health'],
    ARRAY['telefone','teleˈfoni','电话','phone','technology'],
    ARRAY['computador','kõputaˈdor','电脑','computer','technology'],
    ARRAY['internet','ĩterˈnɛtʃi','网络','internet','technology'],
    ARRAY['mensagem','mẽˈsaʒẽj','消息','message','technology'],
    ARRAY['senha','ˈseɲɐ','密码','password','technology'],
    ARRAY['vermelho','verˈmeʎu','红色','red','colors'],
    ARRAY['azul','aˈzuw','蓝色','blue','colors'],
    ARRAY['verde','ˈverdi','绿色','green','colors'],
    ARRAY['amarelo','amaˈɾelu','黄色','yellow','colors'],
    ARRAY['branco','ˈbɾɐ̃ku','白色','white','colors'],
    ARRAY['preto','ˈpɾetu','黑色','black','colors'],
    ARRAY['cinza','ˈsĩzɐ','灰色','gray','colors'],
    ARRAY['laranja','laˈɾɐ̃ʒɐ','橙色','orange','colors'],
    ARRAY['rosa','ˈʁɔzɐ','粉色','pink','colors'],
    ARRAY['marrom','maˈʁõ','棕色','brown','colors'],
    ARRAY['eu','ew','我','I','pronouns'],
    ARRAY['você','voˈse','你','you (Brazil)','pronouns'],
    ARRAY['ele','ˈeli','他','he','pronouns'],
    ARRAY['ela','ˈɛlɐ','她','she','pronouns'],
    ARRAY['nós','nɔʃ','我们','we','pronouns'],
    ARRAY['vocês','voˈseʃ','你们','you (plural)','pronouns'],
    ARRAY['eles','ˈeliʃ','他们','they (m)','pronouns'],
    ARRAY['este','ˈeʃtʃi','这个','this','demonstratives'],
    ARRAY['aquele','aˈkeli','那个','that','demonstratives'],
    ARRAY['aqui','aˈki','这里','here','location'],
    ARRAY['lá','la','那里','there','location'],
    ARRAY['acima','aˈsimɐ','上面','above','location'],
    ARRAY['abaixo','aˈbajʃu','下面','below','location'],
    ARRAY['dentro','ˈdẽtɾu','里面','inside','location'],
    ARRAY['fora','ˈfɔɾɐ','外面','outside','location'],
    ARRAY['perto','ˈpɛʁtu','附近','near','location'],
    ARRAY['longe','ˈlõʒi','远','far','location'],
    ARRAY['direita','diˈɾejtɐ','右边','right','direction'],
    ARRAY['esquerda','eʃˈkeʁdɐ','左边','left','direction'],
    ARRAY['mês','meʃ','月','month','calendar'],
    ARRAY['ano','ˈɐnu','年','year','calendar'],
    ARRAY['semana','siˈmɐnɐ','周','week','calendar'],
    ARRAY['janeiro','ʒɐˈnejɾu','一月','January','months'],
    ARRAY['fevereiro','feveˈɾejɾu','二月','February','months'],
    ARRAY['março','ˈmaʁsu','三月','March','months'],
    ARRAY['abril','aˈbɾiw','四月','April','months'],
    ARRAY['maio','ˈmaju','五月','May','months'],
    ARRAY['junho','ˈʒuɲu','六月','June','months'],
    ARRAY['julho','ˈʒuʎu','七月','July','months'],
    ARRAY['agosto','aˈɡostu','八月','August','months'],
    ARRAY['setembro','seˈtẽbɾu','九月','September','months'],
    ARRAY['outubro','owˈtubɾu','十月','October','months'],
    ARRAY['novembro','noˈvẽbɾu','十一月','November','months'],
    ARRAY['dezembro','diˈzẽbɾu','十二月','December','months']
  ];

  ar_words text[][] := ARRAY[
    ARRAY['مرحبا','marḥaban','你好','hello','greeting'],
    ARRAY['أهلاً','ʾahlan','欢迎','hi / welcome','greeting'],
    ARRAY['السلام عليكم','as-salāmu ʿalaykum','你好（问候）','peace be upon you','greeting'],
    ARRAY['وعليكم السلام','wa-ʿalaykum as-salām','你好（回应）','and upon you peace','greeting'],
    ARRAY['صباح الخير','ṣabāḥ al-khayr','早上好','good morning','greeting'],
    ARRAY['مساء الخير','masāʾ al-khayr','晚上好','good evening','greeting'],
    ARRAY['مع السلامة','maʿa as-salāma','再见','goodbye','greeting'],
    ARRAY['شكراً','shukran','谢谢','thank you','courtesy'],
    ARRAY['عفواً','ʿafwan','不客气','you''re welcome','courtesy'],
    ARRAY['من فضلك','min faḍlak','请','please (m)','courtesy'],
    ARRAY['آسف','āsif','对不起','sorry (m)','courtesy'],
    ARRAY['نعم','naʿam','是','yes','basic'],
    ARRAY['لا','lā','不','no','basic'],
    ARRAY['كيف حالك','kayfa ḥālak','你好吗','how are you (m)','greeting'],
    ARRAY['بخير','bi-khayr','很好','fine / well','response'],
    ARRAY['اسمي','ismī','我叫','my name is','introduction'],
    ARRAY['تشرفنا','tasharrafnā','幸会','nice to meet you','introduction'],
    ARRAY['أين','ʾayna','哪里','where','question_word'],
    ARRAY['متى','matā','什么时候','when','question_word'],
    ARRAY['كم','kam','多少','how much / many','question_word'],
    ARRAY['لماذا','limādhā','为什么','why','question_word'],
    ARRAY['كيف','kayfa','怎么','how','question_word'],
    ARRAY['من','man','谁','who','question_word'],
    ARRAY['ماذا','mādhā','什么','what','question_word'],
    ARRAY['ماء','māʾ','水','water','food'],
    ARRAY['قهوة','qahwa','咖啡','coffee','food'],
    ARRAY['شاي','shāy','茶','tea','food'],
    ARRAY['حليب','ḥalīb','牛奶','milk','food'],
    ARRAY['عصير','ʿaṣīr','果汁','juice','food'],
    ARRAY['خبز','khubz','面包','bread','food'],
    ARRAY['أرز','ʾuruzz','米饭','rice','food'],
    ARRAY['لحم','laḥm','肉','meat','food'],
    ARRAY['دجاج','dajāj','鸡肉','chicken','food'],
    ARRAY['سمك','samak','鱼','fish','food'],
    ARRAY['خضروات','khaḍrawāt','蔬菜','vegetables','food'],
    ARRAY['فاكهة','fākiha','水果','fruit','food'],
    ARRAY['جبن','jubn','奶酪','cheese','food'],
    ARRAY['بيضة','bayḍa','鸡蛋','egg','food'],
    ARRAY['سكر','sukkar','糖','sugar','food'],
    ARRAY['ملح','milḥ','盐','salt','food'],
    ARRAY['واحد','wāḥid','一','one','numbers'],
    ARRAY['اثنان','ithnan','二','two','numbers'],
    ARRAY['ثلاثة','thalātha','三','three','numbers'],
    ARRAY['أربعة','ʾarbaʿa','四','four','numbers'],
    ARRAY['خمسة','khamsa','五','five','numbers'],
    ARRAY['ستة','sitta','六','six','numbers'],
    ARRAY['سبعة','sabʿa','七','seven','numbers'],
    ARRAY['ثمانية','thamāniya','八','eight','numbers'],
    ARRAY['تسعة','tisʿa','九','nine','numbers'],
    ARRAY['عشرة','ʿashara','十','ten','numbers'],
    ARRAY['عشرون','ʿishrūn','二十','twenty','numbers'],
    ARRAY['مئة','miʾa','百','hundred','numbers'],
    ARRAY['ألف','ʾalf','千','thousand','numbers'],
    ARRAY['الاثنين','al-ithnayn','星期一','Monday','days'],
    ARRAY['الثلاثاء','ath-thulāthāʾ','星期二','Tuesday','days'],
    ARRAY['الأربعاء','al-ʾarbiʿāʾ','星期三','Wednesday','days'],
    ARRAY['الخميس','al-khamīs','星期四','Thursday','days'],
    ARRAY['الجمعة','al-jumuʿa','星期五','Friday','days'],
    ARRAY['السبت','as-sabt','星期六','Saturday','days'],
    ARRAY['الأحد','al-ʾaḥad','星期日','Sunday','days'],
    ARRAY['اليوم','al-yawm','今天','today','time'],
    ARRAY['أمس','ʾams','昨天','yesterday','time'],
    ARRAY['غداً','ghadan','明天','tomorrow','time'],
    ARRAY['صباح','ṣabāḥ','早上','morning','time'],
    ARRAY['مساء','masāʾ','傍晚','evening','time'],
    ARRAY['ليل','layl','夜晚','night','time'],
    ARRAY['الآن','al-ʾān','现在','now','time'],
    ARRAY['بعد','baʿda','之后','after','time'],
    ARRAY['قبل','qabla','之前','before','time'],
    ARRAY['دائماً','dāʾiman','总是','always','time'],
    ARRAY['أبداً','ʾabadan','从不','never','time'],
    ARRAY['بيت','bayt','家','house / home','places'],
    ARRAY['مكتب','maktab','办公室','office','places'],
    ARRAY['مدرسة','madrasa','学校','school','places'],
    ARRAY['مستشفى','mustashfā','医院','hospital','places'],
    ARRAY['مطعم','maṭʿam','餐厅','restaurant','places'],
    ARRAY['محل','maḥall','商店','store / shop','places'],
    ARRAY['سوبرماركت','sūbarmārkit','超市','supermarket','places'],
    ARRAY['بنك','bank','银行','bank','places'],
    ARRAY['صيدلية','ṣaydalīya','药店','pharmacy','places'],
    ARRAY['مطار','maṭār','机场','airport','places'],
    ARRAY['فندق','funduq','酒店','hotel','places'],
    ARRAY['شاطئ','shāṭiʾ','海滩','beach','places'],
    ARRAY['جبل','jabal','山','mountain','nature'],
    ARRAY['نهر','nahr','河流','river','nature'],
    ARRAY['بحر','baḥr','海','sea','nature'],
    ARRAY['غابة','ghāba','森林','forest','nature'],
    ARRAY['سماء','samāʾ','天空','sky','nature'],
    ARRAY['شمس','shams','太阳','sun','nature'],
    ARRAY['قمر','qamar','月亮','moon','nature'],
    ARRAY['نجمة','najma','星星','star','nature'],
    ARRAY['مطر','maṭar','雨','rain','nature'],
    ARRAY['رياح','riyāḥ','风','wind','nature'],
    ARRAY['رجل','rajul','男人','man','people'],
    ARRAY['امرأة','imraʾa','女人','woman','people'],
    ARRAY['طفل','ṭifl','孩子','child','people'],
    ARRAY['صديق','ṣadīq','朋友（男）','friend (m)','people'],
    ARRAY['صديقة','ṣadīqa','朋友（女）','friend (f)','people'],
    ARRAY['أب','ʾab','父亲','father','family'],
    ARRAY['أم','ʾumm','母亲','mother','family'],
    ARRAY['أخ','ʾakh','兄弟','brother','family'],
    ARRAY['أخت','ukht','姐妹','sister','family'],
    ARRAY['ابن','ibn','儿子','son','family'],
    ARRAY['ابنة','ibna','女儿','daughter','family'],
    ARRAY['جد','jadd','祖父','grandfather','family'],
    ARRAY['جدة','jadda','祖母','grandmother','family'],
    ARRAY['زوج','zawj','丈夫','husband','family'],
    ARRAY['زوجة','zawja','妻子','wife','family'],
    ARRAY['كبير','kabīr','大','big','adjectives'],
    ARRAY['صغير','ṣaghīr','小','small','adjectives'],
    ARRAY['جميل','jamīl','漂亮','beautiful','adjectives'],
    ARRAY['قبيح','qabīḥ','丑','ugly','adjectives'],
    ARRAY['جيد','jayyid','好','good','adjectives'],
    ARRAY['سيء','sayʾ','坏','bad','adjectives'],
    ARRAY['جديد','jadīd','新','new','adjectives'],
    ARRAY['قديم','qadīm','旧','old','adjectives'],
    ARRAY['ساخن','sākhin','热','hot','adjectives'],
    ARRAY['بارد','bārid','冷','cold','adjectives'],
    ARRAY['سهل','sahl','容易','easy','adjectives'],
    ARRAY['صعب','ṣaʿb','难','difficult','adjectives'],
    ARRAY['سريع','sarīʿ','快','fast','adjectives'],
    ARRAY['بطيء','baṭīʾ','慢','slow','adjectives'],
    ARRAY['طويل','ṭawīl','高/长','tall / long','adjectives'],
    ARRAY['قصير','qaṣīr','矮/短','short','adjectives'],
    ARRAY['يذهب','yadhhabu','去','to go','verbs'],
    ARRAY['يأتي','yaʾtī','来','to come','verbs'],
    ARRAY['يتكلم','yatakallam','说话','to speak','verbs'],
    ARRAY['يأكل','yaʾkul','吃','to eat','verbs'],
    ARRAY['يشرب','yashrab','喝','to drink','verbs'],
    ARRAY['ينام','yanām','睡觉','to sleep','verbs'],
    ARRAY['يدرس','yadrus','学习','to study','verbs'],
    ARRAY['يفهم','yafham','明白','to understand','verbs'],
    ARRAY['يعرف','yaʿrif','知道','to know','verbs'],
    ARRAY['يريد','yurīd','想要','to want','verbs'],
    ARRAY['يرى','yarā','看','to see','verbs'],
    ARRAY['يسمع','yasmaʿ','听','to hear','verbs'],
    ARRAY['يقرأ','yaqraʾ','读','to read','verbs'],
    ARRAY['يكتب','yaktub','写','to write','verbs'],
    ARRAY['يشتري','yashtarī','买','to buy','verbs'],
    ARRAY['يدفع','yadfa','付钱','to pay','verbs'],
    ARRAY['ينتظر','yantaẓir','等待','to wait','verbs'],
    ARRAY['يساعد','yusāʿid','帮助','to help','verbs'],
    ARRAY['يجد','yajid','找到','to find','verbs'],
    ARRAY['يفتح','yaftaḥ','打开','to open','verbs'],
    ARRAY['يغلق','yughliqu','关闭','to close','verbs'],
    ARRAY['يتصل','yattaṣil','打电话','to call','verbs'],
    ARRAY['قطار','qiṭār','火车','train','travel'],
    ARRAY['حافلة','ḥāfila','公共汽车','bus','travel'],
    ARRAY['سيارة أجرة','sayyārat ʾujra','出租车','taxi','travel'],
    ARRAY['سيارة','sayyāra','汽车','car','travel'],
    ARRAY['دراجة','darrāja','自行车','bicycle','travel'],
    ARRAY['تذكرة','tadhkira','票','ticket','travel'],
    ARRAY['جواز سفر','jawāz safar','护照','passport','travel'],
    ARRAY['حقيبة','ḥaqība','行李','bag / suitcase','travel'],
    ARRAY['خريطة','kharīṭa','地图','map','travel'],
    ARRAY['شارع','shāriʿ','街道','street','city'],
    ARRAY['ميدان','maydān','广场','square / plaza','city'],
    ARRAY['جسر','jisr','桥','bridge','city'],
    ARRAY['حديقة','ḥadīqa','公园','park / garden','city'],
    ARRAY['متحف','matḥaf','博物馆','museum','city'],
    ARRAY['مسجد','masjid','清真寺','mosque','city'],
    ARRAY['مال','māl','钱','money','lifestyle'],
    ARRAY['ثمن','thaman','价格','price','shopping'],
    ARRAY['خصم','khaṣm','折扣','discount','shopping'],
    ARRAY['مقاس','muqās','尺码','size','shopping'],
    ARRAY['لون','lawn','颜色','color','shopping'],
    ARRAY['هدية','hadīya','礼物','gift','shopping'],
    ARRAY['حذاء','ḥidhāʾ','鞋子','shoe','clothing'],
    ARRAY['قبعة','qubbaʿa','帽子','hat','clothing'],
    ARRAY['معطف','miʿṭaf','外套','coat / jacket','clothing'],
    ARRAY['بنطلون','banṭalūn','裤子','trousers','clothing'],
    ARRAY['قميص','qamīṣ','衬衫','shirt','clothing'],
    ARRAY['طبيب','ṭabīb','医生','doctor','health'],
    ARRAY['ألم','ʾalam','疼痛','pain','health'],
    ARRAY['حمى','ḥummā','发烧','fever','health'],
    ARRAY['دواء','dawāʾ','药','medicine','health'],
    ARRAY['حساسية','ḥasāsīya','过敏','allergy','health'],
    ARRAY['طوارئ','ṭawāriʾ','紧急情况','emergency','health'],
    ARRAY['هاتف','hātif','电话','phone','technology'],
    ARRAY['حاسوب','ḥāsūb','电脑','computer','technology'],
    ARRAY['إنترنت','ʾintirniyt','网络','internet','technology'],
    ARRAY['رسالة','risāla','消息','message','technology'],
    ARRAY['كلمة المرور','kalimat al-murūr','密码','password','technology'],
    ARRAY['أحمر','ʾaḥmar','红色','red','colors'],
    ARRAY['أزرق','ʾazraq','蓝色','blue','colors'],
    ARRAY['أخضر','ʾakhḍar','绿色','green','colors'],
    ARRAY['أصفر','ʾaṣfar','黄色','yellow','colors'],
    ARRAY['أبيض','ʾabyaḍ','白色','white','colors'],
    ARRAY['أسود','ʾaswad','黑色','black','colors'],
    ARRAY['رمادي','ramādī','灰色','gray','colors'],
    ARRAY['برتقالي','burtuqālī','橙色','orange','colors'],
    ARRAY['وردي','wardī','粉色','pink','colors'],
    ARRAY['بني','bunnī','棕色','brown','colors'],
    ARRAY['أنا','ʾanā','我','I','pronouns'],
    ARRAY['أنت','ʾanta','你（男）','you (m)','pronouns'],
    ARRAY['هو','huwa','他','he','pronouns'],
    ARRAY['هي','hiya','她','she','pronouns'],
    ARRAY['نحن','naḥnu','我们','we','pronouns'],
    ARRAY['أنتم','ʾantum','你们','you (plural)','pronouns'],
    ARRAY['هم','hum','他们','they','pronouns'],
    ARRAY['هذا','hādhā','这个（男）','this (m)','demonstratives'],
    ARRAY['هذه','hādhihi','这个（女）','this (f)','demonstratives'],
    ARRAY['ذلك','dhālika','那个','that','demonstratives'],
    ARRAY['هنا','hunā','这里','here','location'],
    ARRAY['هناك','hunāka','那里','there','location'],
    ARRAY['فوق','fawqa','上面','above','location'],
    ARRAY['تحت','taḥta','下面','below','location'],
    ARRAY['داخل','dākhil','里面','inside','location'],
    ARRAY['خارج','khārij','外面','outside','location'],
    ARRAY['قريب','qarīb','附近','near','location'],
    ARRAY['بعيد','baʿīd','远','far','location'],
    ARRAY['يمين','yamīn','右边','right','direction'],
    ARRAY['يسار','yasār','左边','left','direction'],
    ARRAY['مستقيم','mustaqīm','直走','straight','direction'],
    ARRAY['شهر','shahr','月','month','calendar'],
    ARRAY['سنة','sana','年','year','calendar'],
    ARRAY['أسبوع','ʾusbūʿ','周','week','calendar'],
    ARRAY['يناير','yanāyir','一月','January','months'],
    ARRAY['فبراير','fibrāyir','二月','February','months'],
    ARRAY['مارس','māris','三月','March','months'],
    ARRAY['أبريل','ʾabrīl','四月','April','months'],
    ARRAY['مايو','māyū','五月','May','months'],
    ARRAY['يونيو','yūnyū','六月','June','months'],
    ARRAY['يوليو','yūlyū','七月','July','months'],
    ARRAY['أغسطس','ʾaghusṭus','八月','August','months'],
    ARRAY['سبتمبر','sibtambar','九月','September','months'],
    ARRAY['أكتوبر','ʾuktūbar','十月','October','months'],
    ARRAY['نوفمبر','nūfambar','十一月','November','months'],
    ARRAY['ديسمبر','dīsambar','十二月','December','months']
  ];

  zh_words text[][] := ARRAY[
    ARRAY['你好','nǐ hǎo','你好','hello','greeting'],
    ARRAY['您好','nín hǎo','您好（正式）','hello (formal)','greeting'],
    ARRAY['早上好','zǎoshang hǎo','早上好','good morning','greeting'],
    ARRAY['下午好','xiàwǔ hǎo','下午好','good afternoon','greeting'],
    ARRAY['晚上好','wǎnshang hǎo','晚上好','good evening','greeting'],
    ARRAY['再见','zàijiàn','再见','goodbye','greeting'],
    ARRAY['谢谢','xièxie','谢谢','thank you','courtesy'],
    ARRAY['不客气','bú kèqi','不客气','you''re welcome','courtesy'],
    ARRAY['请','qǐng','请','please','courtesy'],
    ARRAY['对不起','duìbuqǐ','对不起','sorry','courtesy'],
    ARRAY['没关系','méi guānxi','没关系','no problem','courtesy'],
    ARRAY['是','shì','是','yes / is','basic'],
    ARRAY['不','bù','不','no / not','basic'],
    ARRAY['好的','hǎo de','好的','okay','basic'],
    ARRAY['你好吗','nǐ hǎo ma','你好吗','how are you','greeting'],
    ARRAY['我很好','wǒ hěn hǎo','我很好','I''m fine','response'],
    ARRAY['还好','hái hǎo','还好','so-so / not bad','response'],
    ARRAY['我叫','wǒ jiào','我叫','my name is','introduction'],
    ARRAY['幸会','xìnghuì','幸会','nice to meet you','introduction'],
    ARRAY['在哪里','zài nǎlǐ','在哪里','where is','question_word'],
    ARRAY['什么时候','shénme shíhou','什么时候','when','question_word'],
    ARRAY['多少钱','duōshao qián','多少钱','how much (money)','question_word'],
    ARRAY['为什么','wèishénme','为什么','why','question_word'],
    ARRAY['怎么','zěnme','怎么','how','question_word'],
    ARRAY['谁','shuí','谁','who','question_word'],
    ARRAY['什么','shénme','什么','what','question_word'],
    ARRAY['水','shuǐ','水','water','food'],
    ARRAY['茶','chá','茶','tea','food'],
    ARRAY['咖啡','kāfēi','咖啡','coffee','food'],
    ARRAY['牛奶','niúnǎi','牛奶','milk','food'],
    ARRAY['果汁','guǒzhī','果汁','juice','food'],
    ARRAY['啤酒','píjiǔ','啤酒','beer','food'],
    ARRAY['白酒','báijiǔ','白酒','Chinese spirits','food'],
    ARRAY['米饭','mǐfàn','米饭','steamed rice','food'],
    ARRAY['面条','miàntiáo','面条','noodles','food'],
    ARRAY['包子','bāozi','包子','steamed bun','food'],
    ARRAY['饺子','jiǎozi','饺子','dumplings','food'],
    ARRAY['面包','miànbāo','面包','bread','food'],
    ARRAY['肉','ròu','肉','meat','food'],
    ARRAY['鸡肉','jīròu','鸡肉','chicken','food'],
    ARRAY['猪肉','zhūròu','猪肉','pork','food'],
    ARRAY['牛肉','niúròu','牛肉','beef','food'],
    ARRAY['鱼','yú','鱼','fish','food'],
    ARRAY['蔬菜','shūcài','蔬菜','vegetables','food'],
    ARRAY['水果','shuǐguǒ','水果','fruit','food'],
    ARRAY['鸡蛋','jīdàn','鸡蛋','egg','food'],
    ARRAY['豆腐','dòufu','豆腐','tofu','food'],
    ARRAY['辣椒','làjiāo','辣椒','chili pepper','food'],
    ARRAY['酱油','jiàngyóu','酱油','soy sauce','food'],
    ARRAY['糖','táng','糖','sugar','food'],
    ARRAY['盐','yán','盐','salt','food'],
    ARRAY['一','yī','一','one','numbers'],
    ARRAY['二','èr','二','two','numbers'],
    ARRAY['三','sān','三','three','numbers'],
    ARRAY['四','sì','四','four','numbers'],
    ARRAY['五','wǔ','五','five','numbers'],
    ARRAY['六','liù','六','six','numbers'],
    ARRAY['七','qī','七','seven','numbers'],
    ARRAY['八','bā','八','eight','numbers'],
    ARRAY['九','jiǔ','九','nine','numbers'],
    ARRAY['十','shí','十','ten','numbers'],
    ARRAY['百','bǎi','百','hundred','numbers'],
    ARRAY['千','qiān','千','thousand','numbers'],
    ARRAY['万','wàn','万','ten thousand','numbers'],
    ARRAY['亿','yì','亿','100 million','numbers'],
    ARRAY['星期一','xīngqī yī','星期一','Monday','days'],
    ARRAY['星期二','xīngqī èr','星期二','Tuesday','days'],
    ARRAY['星期三','xīngqī sān','星期三','Wednesday','days'],
    ARRAY['星期四','xīngqī sì','星期四','Thursday','days'],
    ARRAY['星期五','xīngqī wǔ','星期五','Friday','days'],
    ARRAY['星期六','xīngqī liù','星期六','Saturday','days'],
    ARRAY['星期日','xīngqī rì','星期日','Sunday','days'],
    ARRAY['今天','jīntiān','今天','today','time'],
    ARRAY['昨天','zuótiān','昨天','yesterday','time'],
    ARRAY['明天','míngtiān','明天','tomorrow','time'],
    ARRAY['早上','zǎoshang','早上','morning','time'],
    ARRAY['下午','xiàwǔ','下午','afternoon','time'],
    ARRAY['晚上','wǎnshang','晚上','evening / night','time'],
    ARRAY['现在','xiànzài','现在','now','time'],
    ARRAY['以后','yǐhòu','以后','after / later','time'],
    ARRAY['以前','yǐqián','以前','before','time'],
    ARRAY['总是','zǒngshì','总是','always','time'],
    ARRAY['从不','cóng bù','从不','never','time'],
    ARRAY['经常','jīngcháng','经常','often','time'],
    ARRAY['家','jiā','家','home / family','places'],
    ARRAY['办公室','bàngōngshì','办公室','office','places'],
    ARRAY['学校','xuéxiào','学校','school','places'],
    ARRAY['医院','yīyuàn','医院','hospital','places'],
    ARRAY['餐厅','cāntīng','餐厅','restaurant','places'],
    ARRAY['商店','shāngdiàn','商店','store / shop','places'],
    ARRAY['超市','chāoshì','超市','supermarket','places'],
    ARRAY['银行','yínháng','银行','bank','places'],
    ARRAY['药店','yàodiàn','药店','pharmacy','places'],
    ARRAY['机场','jīchǎng','机场','airport','places'],
    ARRAY['酒店','jiǔdiàn','酒店','hotel','places'],
    ARRAY['海滩','hǎitān','海滩','beach','places'],
    ARRAY['图书馆','túshūguǎn','图书馆','library','places'],
    ARRAY['地铁站','dìtiě zhàn','地铁站','subway station','places'],
    ARRAY['山','shān','山','mountain','nature'],
    ARRAY['河','hé','河','river','nature'],
    ARRAY['海','hǎi','海','sea','nature'],
    ARRAY['湖','hú','湖','lake','nature'],
    ARRAY['森林','sēnlín','森林','forest','nature'],
    ARRAY['天空','tiānkōng','天空','sky','nature'],
    ARRAY['太阳','tàiyáng','太阳','sun','nature'],
    ARRAY['月亮','yuèliang','月亮','moon','nature'],
    ARRAY['星星','xīngxing','星星','star','nature'],
    ARRAY['雨','yǔ','雨','rain','nature'],
    ARRAY['雪','xuě','雪','snow','nature'],
    ARRAY['风','fēng','风','wind','nature'],
    ARRAY['男人','nánrén','男人','man','people'],
    ARRAY['女人','nǚrén','女人','woman','people'],
    ARRAY['孩子','háizi','孩子','child','people'],
    ARRAY['朋友','péngyou','朋友','friend','people'],
    ARRAY['同事','tóngshì','同事','colleague','people'],
    ARRAY['邻居','línjū','邻居','neighbor','people'],
    ARRAY['父亲','fùqīn','父亲','father','family'],
    ARRAY['母亲','mǔqīn','母亲','mother','family'],
    ARRAY['兄弟','xiōngdì','兄弟','brother','family'],
    ARRAY['姐妹','jiěmèi','姐妹','sister','family'],
    ARRAY['儿子','érzi','儿子','son','family'],
    ARRAY['女儿','nǚér','女儿','daughter','family'],
    ARRAY['爷爷','yéye','爷爷','paternal grandfather','family'],
    ARRAY['奶奶','nǎinai','奶奶','paternal grandmother','family'],
    ARRAY['外公','wàigōng','外公','maternal grandfather','family'],
    ARRAY['外婆','wàipó','外婆','maternal grandmother','family'],
    ARRAY['丈夫','zhàngfu','丈夫','husband','family'],
    ARRAY['妻子','qīzi','妻子','wife','family'],
    ARRAY['大','dà','大','big','adjectives'],
    ARRAY['小','xiǎo','小','small','adjectives'],
    ARRAY['漂亮','piàoliang','漂亮','beautiful','adjectives'],
    ARRAY['丑','chǒu','丑','ugly','adjectives'],
    ARRAY['好','hǎo','好','good','adjectives'],
    ARRAY['坏','huài','坏','bad','adjectives'],
    ARRAY['新','xīn','新','new','adjectives'],
    ARRAY['旧','jiù','旧','old','adjectives'],
    ARRAY['热','rè','热','hot','adjectives'],
    ARRAY['冷','lěng','冷','cold','adjectives'],
    ARRAY['容易','róngyì','容易','easy','adjectives'],
    ARRAY['难','nán','难','difficult','adjectives'],
    ARRAY['快','kuài','快','fast','adjectives'],
    ARRAY['慢','màn','慢','slow','adjectives'],
    ARRAY['高','gāo','高','tall / high','adjectives'],
    ARRAY['矮','ǎi','矮','short','adjectives'],
    ARRAY['贵','guì','贵','expensive','adjectives'],
    ARRAY['便宜','piányí','便宜','cheap','adjectives'],
    ARRAY['忙','máng','忙','busy','adjectives'],
    ARRAY['有','yǒu','有','to have','verbs'],
    ARRAY['做','zuò','做','to do / make','verbs'],
    ARRAY['去','qù','去','to go','verbs'],
    ARRAY['来','lái','来','to come','verbs'],
    ARRAY['说','shuō','说','to speak / say','verbs'],
    ARRAY['吃','chī','吃','to eat','verbs'],
    ARRAY['喝','hē','喝','to drink','verbs'],
    ARRAY['睡觉','shuìjiào','睡觉','to sleep','verbs'],
    ARRAY['工作','gōngzuò','工作','to work','verbs'],
    ARRAY['学习','xuéxí','学习','to study / learn','verbs'],
    ARRAY['明白','míngbai','明白','to understand','verbs'],
    ARRAY['知道','zhīdào','知道','to know','verbs'],
    ARRAY['能','néng','能','to be able / can','verbs'],
    ARRAY['想','xiǎng','想','to want / think','verbs'],
    ARRAY['要','yào','要','to want / need','verbs'],
    ARRAY['看','kàn','看','to see / look / watch','verbs'],
    ARRAY['听','tīng','听','to listen / hear','verbs'],
    ARRAY['读','dú','读','to read','verbs'],
    ARRAY['写','xiě','写','to write','verbs'],
    ARRAY['买','mǎi','买','to buy','verbs'],
    ARRAY['卖','mài','卖','to sell','verbs'],
    ARRAY['付钱','fù qián','付钱','to pay','verbs'],
    ARRAY['等','děng','等','to wait','verbs'],
    ARRAY['帮助','bāngzhù','帮助','to help','verbs'],
    ARRAY['找','zhǎo','找','to find / look for','verbs'],
    ARRAY['打开','dǎkāi','打开','to open','verbs'],
    ARRAY['关','guān','关','to close','verbs'],
    ARRAY['打电话','dǎ diànhuà','打电话','to call','verbs'],
    ARRAY['预订','yùdìng','预订','to reserve','travel'],
    ARRAY['出发','chūfā','出发','to depart','travel'],
    ARRAY['到达','dàodá','到达','to arrive','travel'],
    ARRAY['火车','huǒchē','火车','train','travel'],
    ARRAY['地铁','dìtiě','地铁','subway / metro','travel'],
    ARRAY['公共汽车','gōnggòng qìchē','公共汽车','bus','travel'],
    ARRAY['出租车','chūzū chē','出租车','taxi','travel'],
    ARRAY['汽车','qìchē','汽车','car','travel'],
    ARRAY['飞机','fēijī','飞机','airplane','travel'],
    ARRAY['自行车','zìxíngchē','自行车','bicycle','travel'],
    ARRAY['车票','chē piào','车票','ticket','travel'],
    ARRAY['护照','hùzhào','护照','passport','travel'],
    ARRAY['行李','xíngli','行李','luggage','travel'],
    ARRAY['地图','dìtú','地图','map','travel'],
    ARRAY['街道','jiēdào','街道','street','city'],
    ARRAY['广场','guǎngchǎng','广场','square / plaza','city'],
    ARRAY['桥','qiáo','桥','bridge','city'],
    ARRAY['公园','gōngyuán','公园','park','city'],
    ARRAY['博物馆','bówùguǎn','博物馆','museum','city'],
    ARRAY['寺庙','sìmiào','寺庙','temple','city'],
    ARRAY['钱','qián','钱','money','lifestyle'],
    ARRAY['价格','jiàgé','价格','price','shopping'],
    ARRAY['折扣','zhékòu','折扣','discount','shopping'],
    ARRAY['尺码','chǐmǎ','尺码','size','shopping'],
    ARRAY['颜色','yánsè','颜色','color','shopping'],
    ARRAY['礼物','lǐwù','礼物','gift','shopping'],
    ARRAY['收银台','shōuyín tái','收银台','cashier','shopping'],
    ARRAY['衣服','yīfu','衣服','clothing','clothing'],
    ARRAY['鞋子','xiézi','鞋子','shoes','clothing'],
    ARRAY['帽子','màozi','帽子','hat','clothing'],
    ARRAY['外套','wàitào','外套','coat / jacket','clothing'],
    ARRAY['裤子','kùzi','裤子','trousers','clothing'],
    ARRAY['衬衫','chènshān','衬衫','shirt','clothing'],
    ARRAY['医生','yīshēng','医生','doctor','health'],
    ARRAY['护士','hùshi','护士','nurse','health'],
    ARRAY['疼痛','téngtòng','疼痛','pain','health'],
    ARRAY['发烧','fāshāo','发烧','fever','health'],
    ARRAY['药','yào','药','medicine','health'],
    ARRAY['过敏','guòmǐn','过敏','allergy','health'],
    ARRAY['紧急情况','jǐnjí qíngkuàng','紧急情况','emergency','health'],
    ARRAY['手机','shǒujī','手机','mobile phone','technology'],
    ARRAY['电脑','diànnǎo','电脑','computer','technology'],
    ARRAY['网络','wǎngluò','网络','internet / network','technology'],
    ARRAY['短信','duǎnxìn','短信','text message','technology'],
    ARRAY['密码','mìmǎ','密码','password','technology'],
    ARRAY['红色','hóngsè','红色','red','colors'],
    ARRAY['蓝色','lánsè','蓝色','blue','colors'],
    ARRAY['绿色','lǜsè','绿色','green','colors'],
    ARRAY['黄色','huángsè','黄色','yellow','colors'],
    ARRAY['白色','báisè','白色','white','colors'],
    ARRAY['黑色','hēisè','黑色','black','colors'],
    ARRAY['灰色','huīsè','灰色','gray','colors'],
    ARRAY['橙色','chéngsè','橙色','orange','colors'],
    ARRAY['粉色','fěnsè','粉色','pink','colors'],
    ARRAY['棕色','zōngsè','棕色','brown','colors'],
    ARRAY['我','wǒ','我','I / me','pronouns'],
    ARRAY['你','nǐ','你','you (singular)','pronouns'],
    ARRAY['他','tā','他','he','pronouns'],
    ARRAY['她','tā-f','她','she','pronouns'],
    ARRAY['我们','wǒmen','我们','we','pronouns'],
    ARRAY['你们','nǐmen','你们','you (plural)','pronouns'],
    ARRAY['他们','tāmen','他们','they','pronouns'],
    ARRAY['这','zhè','这','this','demonstratives'],
    ARRAY['那','nà','那','that','demonstratives'],
    ARRAY['这里','zhèlǐ','这里','here','location'],
    ARRAY['那里','nàlǐ','那里','there','location'],
    ARRAY['上面','shàngmiàn','上面','above','location'],
    ARRAY['下面','xiàmiàn','下面','below','location'],
    ARRAY['里面','lǐmiàn','里面','inside','location'],
    ARRAY['外面','wàimiàn','外面','outside','location'],
    ARRAY['附近','fùjìn','附近','nearby','location'],
    ARRAY['远','yuǎn','远','far','location'],
    ARRAY['右边','yòubiān','右边','right','direction'],
    ARRAY['左边','zuǒbiān','左边','left','direction'],
    ARRAY['直走','zhí zǒu','直走','go straight','direction'],
    ARRAY['月','yuè','月','month','calendar'],
    ARRAY['年','nián','年','year','calendar'],
    ARRAY['周','zhōu','周','week','calendar'],
    ARRAY['一月','yīyuè','一月','January','months'],
    ARRAY['二月','èryuè','二月','February','months'],
    ARRAY['三月','sānyuè','三月','March','months'],
    ARRAY['四月','sìyuè','四月','April','months'],
    ARRAY['五月','wǔyuè','五月','May','months'],
    ARRAY['六月','liùyuè','六月','June','months'],
    ARRAY['七月','qīyuè','七月','July','months'],
    ARRAY['八月','bāyuè','八月','August','months'],
    ARRAY['九月','jiǔyuè','九月','September','months'],
    ARRAY['十月','shíyuè','十月','October','months'],
    ARRAY['十一月','shíyīyuè','十一月','November','months'],
    ARRAY['十二月','shíèryuè','十二月','December','months'],
    ARRAY['汉字','hànzì','汉字','Chinese character','advanced'],
    ARRAY['声调','shēngdiào','声调','tone','advanced'],
    ARRAY['拼音','pīnyīn','拼音','pinyin romanization','advanced'],
    ARRAY['成语','chéngyǔ','成语','idiom (4-char)','advanced'],
    ARRAY['量词','liàngcí','量词','measure word','advanced'],
    ARRAY['虽然','suīrán','虽然','although','advanced'],
    ARRAY['因为','yīnwèi','因为','because','advanced'],
    ARRAY['所以','suǒyǐ','所以','therefore','advanced'],
    ARRAY['但是','dànshì','但是','but / however','advanced'],
    ARRAY['而且','érqiě','而且','moreover / and also','advanced'],
    ARRAY['如果','rúguǒ','如果','if','advanced'],
    ARRAY['只要','zhǐyào','只要','as long as','advanced'],
    ARRAY['不仅','bùjǐn','不仅','not only','advanced'],
    ARRAY['既然','jìrán','既然','since / given that','advanced'],
    ARRAY['尽管','jǐnguǎn','尽管','even though','advanced']
  ];

  w text[];
  i integer;
BEGIN
  -- Italian vocab
  i := 1;
  FOREACH w SLICE 1 IN ARRAY it_words LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index, created_at)
    VALUES ('it', w[1], w[2], w[3], w[4], w[5], 'N1', i, now())
    ON CONFLICT DO NOTHING;
    i := i + 1;
  END LOOP;

  -- Portuguese vocab
  i := 1;
  FOREACH w SLICE 1 IN ARRAY pt_words LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index, created_at)
    VALUES ('pt', w[1], w[2], w[3], w[4], w[5], 'N1', i, now())
    ON CONFLICT DO NOTHING;
    i := i + 1;
  END LOOP;

  -- Arabic vocab
  i := 1;
  FOREACH w SLICE 1 IN ARRAY ar_words LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index, created_at)
    VALUES ('ar', w[1], w[2], w[3], w[4], w[5], 'N1', i, now())
    ON CONFLICT DO NOTHING;
    i := i + 1;
  END LOOP;

  -- Chinese advanced vocab
  i := 1;
  FOREACH w SLICE 1 IN ARRAY zh_words LOOP
    INSERT INTO vocabulary_items (language_code, word, reading, meaning_zh, meaning_en, tag, level, order_index, created_at)
    VALUES ('zh', w[1], w[2], w[3], w[4], w[5], 'N1', i, now())
    ON CONFLICT DO NOTHING;
    i := i + 1;
  END LOOP;
END $$;
